<?php

use App\Author;
use Illuminate\Database\Seeder;

class AuthorsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {        
// Author::create(['name' => '1drus', 'singkatan' => 'IDR']);
Author::create(['name' => 'A chdiat K Mihardjo', 'singkatan' => 'MIH']);
Author::create(['name' => 'A. Kadarmanta', 'singkatan' => 'KAD']);
Author::create(['name' => 'A. Kristiawan Muryanto', 'singkatan' => 'MUR']);
Author::create(['name' => 'A.A Pardji Tirna', 'singkatan' => 'TIR']);
Author::create(['name' => 'A.A. Navis', 'singkatan' => 'NAV']);
Author::create(['name' => 'A.Chaeder Alwasila M.A.Ph.D', 'singkatan' => 'ALW']);
Author::create(['name' => 'A.G. Tamprin', 'singkatan' => 'TAM']);
Author::create(['name' => 'A.Handoyo', 'singkatan' => 'HAN']);
Author::create(['name' => 'A.Juryana sudrajat', 'singkatan' => 'SUD']);
Author::create(['name' => 'A.Kristiawan Muryanto', 'singkatan' => 'MUR']);
Author::create(['name' => 'A.M Hirin', 'singkatan' => 'HIR']);
Author::create(['name' => 'A.Sugino sudrajat', 'singkatan' => 'SUD']);
Author::create(['name' => 'A.Taufiq Hidayatullah', 'singkatan' => 'TAU']);
Author::create(['name' => 'Abd Rahman', 'singkatan' => 'RAH']);
Author::create(['name' => 'Abd. Bin Nuh, Oemar Bakry', 'singkatan' => 'NUH']);
Author::create(['name' => 'Abdul Aziz', 'singkatan' => 'AZI']);
Author::create(['name' => 'Abdul Aziz Saefudin', 'singkatan' => 'SAE']);
Author::create(['name' => 'Abdul Ghofir', 'singkatan' => 'TRI']);
Author::create(['name' => 'Abdul Kadir', 'singkatan' => 'ABD']);
Author::create(['name' => 'Abdul Kadir', 'singkatan' => 'KAD']);
Author::create(['name' => 'Abdul Kharis Almasyari, S.E., Akt.', 'singkatan' => 'ALM']);
Author::create(['name' => 'Abdul rozak zaidan', 'singkatan' => 'ZAI']);
Author::create(['name' => 'Abdul Wachid B.S', 'singkatan' => 'WAC']);
Author::create(['name' => 'Abdullah Abdul Aziz Al Aidan', 'singkatan' => 'ABD']);
Author::create(['name' => 'Abdullah Gymnastiar', 'singkatan' => 'GYM']);
Author::create(['name' => 'Abdurrahman An Nahlawi', 'singkatan' => 'NAH']);
Author::create(['name' => 'Abdy Yuhana, SH, MH', 'singkatan' => 'YUH']);
Author::create(['name' => 'Abidah El Khadieqy', 'singkatan' => 'KHA']);
Author::create(['name' => 'Abu Yahya F. Haramain', 'singkatan' => 'YAH']);
Author::create(['name' => 'Aburrahman Al-Mukaffi', 'singkatan' => 'MUK']);
Author::create(['name' => 'Achdiat Michardja', 'singkatan' => 'MIC']);
Author::create(['name' => 'Achmad Sjaichu,S,Pd', 'singkatan' => 'SJA']);
Author::create(['name' => 'Ade Yunisa', 'singkatan' => 'YUN']);
Author::create(['name' => 'Adhi Prasetio', 'singkatan' => 'ADH']);
Author::create(['name' => 'Adhyaksa Dault', 'singkatan' => 'DAU']);
Author::create(['name' => 'Adhyaksa Doult', 'singkatan' => 'DOU']);
Author::create(['name' => 'Adi', 'singkatan' => 'ADI']);
Author::create(['name' => 'Adi Asmara, Bohari Yusuf, Susilo', 'singkatan' => 'ASM']);
Author::create(['name' => 'Adi Kusrianto', 'singkatan' => 'KUS']);
Author::create(['name' => 'Adi Nugroho', 'singkatan' => 'ADI']);
Author::create(['name' => 'Adi Wong J', 'singkatan' => 'WON']);
Author::create(['name' => 'Adiba A. Soebachman', 'singkatan' => 'SOE']);
Author::create(['name' => 'Aditya', 'singkatan' => 'ADI']);
Author::create(['name' => 'Aditya S.T', 'singkatan' => 'ADI']);
Author::create(['name' => 'Agatha Cristie', 'singkatan' => 'AGT']);
Author::create(['name' => 'Agnes Davonar', 'singkatan' => 'DAV']);
Author::create(['name' => 'Agung Feryanto', 'singkatan' => 'FER']);
Author::create(['name' => 'Agung Nugroho, S.pd.', 'singkatan' => 'NUG']);
Author::create(['name' => 'agung Tri Haryanta', 'singkatan' => 'HAR']);
Author::create(['name' => 'Agung Tri Haryanta, Eko Sujatmiko', 'singkatan' => 'HAR']);
Author::create(['name' => 'Agus Budiyanto', 'singkatan' => 'BUD']);
Author::create(['name' => 'Agus Kurniawan', 'singkatan' => 'KUR']);
Author::create(['name' => 'Agus widyantoro,Dkk', 'singkatan' => 'WID']);
Author::create(['name' => 'Ahmad Fuadi', 'singkatan' => 'FUA']);
Author::create(['name' => 'Ahmad Gaus', 'singkatan' => 'GAU']);
Author::create(['name' => 'Ahmad Iskhak, Yustina', 'singkatan' => 'ISK']);
Author::create(['name' => 'Ahmad Thommy H, S.S', 'singkatan' => 'THO']);
Author::create(['name' => 'Ahmadu', 'singkatan' => 'AHM']);
Author::create(['name' => 'Ahmadun Y. Herfanda', 'singkatan' => 'HER']);
Author::create(['name' => 'Ainul haris umar thayib', 'singkatan' => 'RAB']);
Author::create(['name' => 'Ainun Muhammad', 'singkatan' => 'MUH']);
Author::create(['name' => 'Ajip Rosidi', 'singkatan' => 'ROS']);
Author::create(['name' => 'Ajuh Khamdani', 'singkatan' => 'KHA']);
Author::create(['name' => 'Al Ries & Jack Trout', 'singkatan' => 'RIE']);
Author::create(['name' => 'Alam S. Henri Hidayat', 'singkatan' => 'HID']);
Author::create(['name' => 'Alamul huda, ST', 'singkatan' => 'HUD']);
Author::create(['name' => 'Aldo Sahala', 'singkatan' => 'ALD']);
Author::create(['name' => 'Ali Irfan', 'singkatan' => 'IRF']);
Author::create(['name' => 'Ali Muakhir', 'singkatan' => 'MUA']);
Author::create(['name' => 'Ali muhson,Miyanto', 'singkatan' => 'MUH']);
Author::create(['name' => 'Ali Nurdin', 'singkatan' => 'NUR']);
Author::create(['name' => 'Alison Dupernex', 'singkatan' => 'DUP']);
Author::create(['name' => 'Alvi Syahrin', 'singkatan' => 'ALV']);
Author::create(['name' => 'Amelia Zuliyanti Siregar,Dkk', 'singkatan' => 'SIR']);
Author::create(['name' => 'Amin Suparihatini', 'singkatan' => 'SUP']);
Author::create(['name' => 'Amin Suprihartini', 'singkatan' => 'SUP']);
Author::create(['name' => 'Amin Suprihartini,S.pd', 'singkatan' => 'SUP']);
Author::create(['name' => 'Amin Suprihartini.dkk', 'singkatan' => 'SUP']);
Author::create(['name' => 'Amin Suprihatini', 'singkatan' => 'SUP']);
Author::create(['name' => 'Aminudin, H.Pardi Yatim,Dkk', 'singkatan' => 'AMI']);
Author::create(['name' => 'Amir Fatah Sofyan, Agus Purwanto', 'singkatan' => 'SOF']);
Author::create(['name' => 'Amir tengku ramli & Erlin Trisyulianti', 'singkatan' => 'RAM']);
Author::create(['name' => 'amirudin ansori,antoni salim', 'singkatan' => 'ANS']);
Author::create(['name' => 'Amran Musholi', 'singkatan' => 'MUS']);
Author::create(['name' => 'Amran Y.S. Chaniago,BA', 'singkatan' => 'CHA']);
Author::create(['name' => 'Amy B middleman & kate gruenwald pfeifer', 'singkatan' => 'MAN']);
Author::create(['name' => 'Amy B middleman & kate gruenwald pfeifer', 'singkatan' => 'MID']);
Author::create(['name' => 'Ananda Hamida', 'singkatan' => 'HAM']);
Author::create(['name' => 'Andi & Wahana Komouter', 'singkatan' => 'AND']);
Author::create(['name' => 'Andi Anas', 'singkatan' => 'ANA']);
Author::create(['name' => 'Andi Setiawan, S.Kom', 'singkatan' => 'SET']);
Author::create(['name' => 'Andi Taru Nugroho', 'singkatan' => 'TAR']);
Author::create(['name' => 'Anditya & M.Syukri tanjung', 'singkatan' => 'AND']);
Author::create(['name' => 'Andr Setyawan', 'singkatan' => 'SET']);
Author::create(['name' => 'Andrea Hirata', 'singkatan' => 'HIR']);
Author::create(['name' => 'Andri Panduweni', 'singkatan' => 'PAN']);
Author::create(['name' => 'Andri Setyawan', 'singkatan' => 'SET']);
Author::create(['name' => 'Andrias Harefa', 'singkatan' => 'HAR']);
Author::create(['name' => 'Andy Shera', 'singkatan' => 'SHE']);
Author::create(['name' => 'Angga Wibawa', 'singkatan' => 'WIB']);
Author::create(['name' => 'Ani Sri Rahayu, SIP, M.AP', 'singkatan' => 'SRI']);
Author::create(['name' => 'Anjik Sukamaaji & Rianto', 'singkatan' => 'SUK']);
Author::create(['name' => 'Anjik Sukamji,S.Kom dan Rianto S.kom', 'singkatan' => 'SUK']);
Author::create(['name' => 'Anjrah Mintana, T.Adi Wijaya', 'singkatan' => 'MIN']);
Author::create(['name' => 'Anna Mariana', 'singkatan' => 'MAR']);
Author::create(['name' => 'anna WS', 'singkatan' => 'ANN']);
Author::create(['name' => 'Anne Rooney', 'singkatan' => 'ROO']);
Author::create(['name' => 'Antok Tri Prabowo', 'singkatan' => 'PRA']);
Author::create(['name' => 'Anton Adiwiyoto', 'singkatan' => 'ADI']);
Author::create(['name' => 'Anton Kristiadi', 'singkatan' => 'KRI']);
Author::create(['name' => 'Anton Moelyono', 'singkatan' => 'PBDPN']);
Author::create(['name' => 'Anton Suparyanto.S.S', 'singkatan' => 'SUP']);
Author::create(['name' => 'Apkomindo', 'singkatan' => 'APK']);
Author::create(['name' => 'Apriana Nuryanto', 'singkatan' => 'NUR']);
Author::create(['name' => 'Ardison Muhammad', 'singkatan' => 'MUH']);
Author::create(['name' => 'Ari Subekti', 'singkatan' => 'SUB']);
Author::create(['name' => 'aries Heru Prasetyo', 'singkatan' => 'PRA']);
Author::create(['name' => 'Arif Budi Permana', 'singkatan' => 'ARF']);
Author::create(['name' => 'Arif kurniawan', 'singkatan' => 'KUR']);
Author::create(['name' => 'Arifin C Noer', 'singkatan' => 'NOE']);
Author::create(['name' => 'aris darmawan', 'singkatan' => 'ARI']);
Author::create(['name' => 'Arkola', 'singkatan' => 'IND']);
Author::create(['name' => 'Armin, S.Pd, Iwan Setiawan, Sunardi, M.Si', 'singkatan' => 'ARM']);
Author::create(['name' => 'arsewendo Atmowiloto', 'singkatan' => 'ATM']);
Author::create(['name' => 'Arya Dipanegara', 'singkatan' => 'ARY']);
Author::create(['name' => 'Asep D.P, H.S Gumilar', 'singkatan' => 'GUM']);
Author::create(['name' => 'Askari Azkin, Yudha Purwanto,ST', 'singkatan' => 'AZK']);
Author::create(['name' => 'Aslimeri,dkk', 'singkatan' => 'ASL']);
Author::create(['name' => 'Asma Nadia', 'singkatan' => 'NAD']);
Author::create(['name' => 'Asma Nadia, dkk', 'singkatan' => 'NAD']);
Author::create(['name' => 'Asman Aswan', 'singkatan' => 'ASW']);
Author::create(['name' => 'Asrul Sari', 'singkatan' => 'SAR']);
Author::create(['name' => 'Atep Adya Barata,Dkk', 'singkatan' => 'BAR']);
Author::create(['name' => 'Athailah', 'singkatan' => 'ATH']);
Author::create(['name' => 'Ating Tedjasutisna', 'singkatan' => 'TED']);
Author::create(['name' => 'Atty Srie Sulastri', 'singkatan' => 'SUL']);
Author::create(['name' => 'Aunur Rafiq Mulyarto', 'singkatan' => 'MUL']);
Author::create(['name' => 'Awan pribadi Basuki', 'singkatan' => 'PRI']);
Author::create(['name' => 'Ayo yahya Heryanto', 'singkatan' => 'HER']);
Author::create(['name' => 'Ayu Resti Rusmini S,pd. Notanie DKK', 'singkatan' => 'RUS']);
Author::create(['name' => 'Azmat margajaya', 'singkatan' => 'MAR']);
Author::create(['name' => 'B. Wisnu Wardhana', 'singkatan' => 'WAR']);
Author::create(['name' => 'B.M.Syamsudin', 'singkatan' => 'SYA']);
Author::create(['name' => 'Bachruddin Jusuf Habibie', 'singkatan' => 'JUS']);
Author::create(['name' => 'bachtiar bima M', 'singkatan' => 'BIM']);
Author::create(['name' => 'Badan standarisasi Nasional', 'singkatan' => 'BSN']);
Author::create(['name' => 'Bagas Prama Ananta', 'singkatan' => 'ANA']);
Author::create(['name' => 'Bagus kurniawan. S.Si', 'singkatan' => 'KUR']);
Author::create(['name' => 'Bahrudin Supardi', 'singkatan' => 'SUP']);
Author::create(['name' => 'bambang Dwiloka & Rati riana', 'singkatan' => 'BAM']);
Author::create(['name' => 'Bambang Prasetyo, S.H.', 'singkatan' => 'PRA']);
Author::create(['name' => 'Bambang Robi\'in', 'singkatan' => 'ROB']);
Author::create(['name' => 'bambang sarwanto', 'singkatan' => 'SAR']);
Author::create(['name' => 'Bambang Suharno', 'singkatan' => 'SUH']);
Author::create(['name' => 'Bambang Suharno & Rochim Armando', 'singkatan' => 'SUH']);
Author::create(['name' => 'Bambang Suteng, Dkk', 'singkatan' => 'SUT']);
Author::create(['name' => 'Bambang Tri Purwanto - Sunardi', 'singkatan' => 'TRI']);
Author::create(['name' => 'Bambang Trim', 'singkatan' => 'TRI']);
Author::create(['name' => 'Bandara cartland', 'singkatan' => 'CAR']);
Author::create(['name' => 'Bandung Arry S, Dkk', 'singkatan' => 'ARR']);
Author::create(['name' => 'Barbara Lynch', 'singkatan' => 'LYN']);
Author::create(['name' => 'bartolomeus Samho', 'singkatan' => 'SAM']);
Author::create(['name' => 'Bat Genoot Sctop', 'singkatan' => 'SCT']);
Author::create(['name' => 'Bebbi oktana', 'singkatan' => 'OKT']);
Author::create(['name' => 'Bebbi Oktara', 'singkatan' => 'OKT']);
Author::create(['name' => 'Benazio Rizki', 'singkatan' => 'RIZ']);
Author::create(['name' => 'Benedicta Rini Widiarti', 'singkatan' => 'WID']);
Author::create(['name' => 'Beni S. Ambarjaya, S.Pd.', 'singkatan' => 'AMB']);
Author::create(['name' => 'Benidicta Rini Widiarti', 'singkatan' => 'WID']);
Author::create(['name' => 'Benny ciptarja', 'singkatan' => 'CIP']);
Author::create(['name' => 'Benny Yong', 'singkatan' => 'YON']);
Author::create(['name' => 'Beranda Agency', 'singkatan' => 'BER']);
Author::create(['name' => 'Bernaridho i.Hutabarat, M.Sc.,OCP', 'singkatan' => 'HUT']);
Author::create(['name' => 'Berry Kercheval', 'singkatan' => 'KER']);
Author::create(['name' => 'Betha Sidik, Ir.Husni Iskandar Pohan,Ir. M.Eng', 'singkatan' => 'SID']);
Author::create(['name' => 'Bidang pembinaan TK/SD Dinas pendidikan prov Kaltim', 'singkatan' => 'BPDPK']);
Author::create(['name' => 'Bill Handley', 'singkatan' => 'HAN']);
Author::create(['name' => 'Bill Welker', 'singkatan' => 'WEL']);
Author::create(['name' => 'Bintang Indonesia Jakarta', 'singkatan' => 'BIN']);
Author::create(['name' => 'Bob foster, Harlin', 'singkatan' => 'FOS']);
Author::create(['name' => 'Brian Brenda', 'singkatan' => 'BRE']);
Author::create(['name' => 'Bryson Gore', 'singkatan' => 'GOR']);
Author::create(['name' => 'Buck Rodgers, Robert L. Shook', 'singkatan' => 'ROD']);
Author::create(['name' => 'Budi Lazarusli, S.H', 'singkatan' => 'LAZ']);
Author::create(['name' => 'Budi Martono, Dkk', 'singkatan' => 'MAR']);
Author::create(['name' => 'Budi Raharjo', 'singkatan' => 'BUD']);
Author::create(['name' => 'Budiman Anwar', 'singkatan' => 'ANW']);
Author::create(['name' => 'Budiyanto', 'singkatan' => 'BUD']);
Author::create(['name' => 'Budiyono', 'singkatan' => 'BUD']);
Author::create(['name' => 'Budiyono,Dkk', 'singkatan' => 'BUD']);
Author::create(['name' => 'Budo Sutedjo S.Kom.MM,Dkk', 'singkatan' => 'SUT']);
Author::create(['name' => 'Bunafir Nugroho', 'singkatan' => 'NUG']);
Author::create(['name' => 'Bunafit Nugroho', 'singkatan' => 'BUN']);
Author::create(['name' => 'Bunafit Nugroho', 'singkatan' => 'NUG']);
Author::create(['name' => 'C.M. Jones & Angela Buxton', 'singkatan' => 'JON']);
Author::create(['name' => 'Carmentyana sitanggang,Dkk', 'singkatan' => 'SIT']);
Author::create(['name' => 'Caroline arnold', 'singkatan' => 'ARN']);
Author::create(['name' => 'Caroline Bingham', 'singkatan' => 'BIN']);
Author::create(['name' => 'Carrie Love', 'singkatan' => 'LOV']);
Author::create(['name' => 'Caturto Priyo N.', 'singkatan' => 'PRI']);
Author::create(['name' => 'Cecep Samsul Hary', 'singkatan' => 'HAR']);
Author::create(['name' => 'Chabibah', 'singkatan' => 'CHA']);
Author::create(['name' => 'Chairani Hanum', 'singkatan' => 'HAN']);
Author::create(['name' => 'Chairil Anwar', 'singkatan' => 'ANW']);
Author::create(['name' => 'Chavchay Syaifullah', 'singkatan' => 'SYA']);
Author::create(['name' => 'Choromaster', 'singkatan' => 'CHO']);
Author::create(['name' => 'Chris harijanto, S.E., M.M.', 'singkatan' => 'HAR']);
Author::create(['name' => 'chris Harijanto. S.E.,M.M', 'singkatan' => 'HAR']);
Author::create(['name' => 'Chris Woodford', 'singkatan' => 'WOO']);
Author::create(['name' => 'Christianus Sigit Sulistya', 'singkatan' => 'SUL']);
Author::create(['name' => 'christopher P.Jargoszuki dan Franklin Potter', 'singkatan' => 'JAR']);
Author::create(['name' => 'Christopher paolini', 'singkatan' => 'CHR']);
Author::create(['name' => 'Christopher Pike', 'singkatan' => 'PIK']);
Author::create(['name' => 'Citra Umbara', 'singkatan' => 'UMB']);
Author::create(['name' => 'Claire buckley', 'singkatan' => 'BUC']);
Author::create(['name' => 'Cliffs quickreview', 'singkatan' => 'QUI']);
Author::create(['name' => 'Clive Gifford', 'singkatan' => 'GIF']);
Author::create(['name' => 'Colin uttley', 'singkatan' => 'UTT']);
Author::create(['name' => 'CV. Pustaka Agung Harapan', 'singkatan' => 'AGU']);
Author::create(['name' => 'D.Bambang Setiono Adi,Dkk', 'singkatan' => 'ADI']);
Author::create(['name' => 'Dan Gable', 'singkatan' => 'GAB']);
Author::create(['name' => 'Danang S. Hadiwardoyo & Heri Prasetyo', 'singkatan' => 'HAD']);
Author::create(['name' => 'Danang Sunyoto', 'singkatan' => 'SUN']);
Author::create(['name' => 'Dandang A. Dahlan', 'singkatan' => 'DAH']);
Author::create(['name' => 'Daniel Agus Maryanto', 'singkatan' => 'MAR']);
Author::create(['name' => 'Daniel King', 'singkatan' => 'KIN']);
Author::create(['name' => 'Danny Mielke', 'singkatan' => 'MIE']);
Author::create(['name' => 'Darliansyah Putra', 'singkatan' => 'PUT']);
Author::create(['name' => 'Darold E.Larson', 'singkatan' => 'LAR']);
Author::create(['name' => 'Datik Taparena', 'singkatan' => 'TAP']);
Author::create(['name' => 'David Cottrell', 'singkatan' => 'COT']);
Author::create(['name' => 'David G. Thomas, MS', 'singkatan' => 'THO']);
Author::create(['name' => 'David Odang', 'singkatan' => 'ODA']);
Author::create(['name' => 'Dawig Roosbiyantana', 'singkatan' => 'ROO']);
Author::create(['name' => 'Deanto', 'singkatan' => 'DEA']);
Author::create(['name' => 'Deasylawati Prasetyaningsih', 'singkatan' => 'PRA']);
Author::create(['name' => 'Dede Domet berry, Michoel Barry, Shonan soudai M.D', 'singkatan' => 'BER']);
Author::create(['name' => 'Dedy Rusmadi', 'singkatan' => 'RUS']);
Author::create(['name' => 'Dedy Suardi', 'singkatan' => 'SUA']);
Author::create(['name' => 'Dendy Sugono', 'singkatan' => 'sug']);
Author::create(['name' => 'Departemen Pendidikan', 'singkatan' => 'PEN']);
Author::create(['name' => 'Departemen Pendidikan Nasional', 'singkatan' => 'DPN']);
Author::create(['name' => 'Departemen pendidikan nasional republik indonesia', 'singkatan' => 'PEN']);
Author::create(['name' => 'depertemen Pendidikan Nasional', 'singkatan' => 'DPN']);
Author::create(['name' => 'Deputi bidang klembagaan koperasi dan UKM', 'singkatan' => 'DEP']);
Author::create(['name' => 'Destin Huru Setiati', 'singkatan' => 'SET']);
Author::create(['name' => 'Devi Puspitasari', 'singkatan' => 'PUS']);
Author::create(['name' => 'Dewi Marsiyah', 'singkatan' => 'MAR']);
Author::create(['name' => 'Dewi Nawangsari', 'singkatan' => 'NAW']);
Author::create(['name' => 'Dewi Nurmayati, Endang sugiarti, Sofyan Mansor.', 'singkatan' => 'NUR']);
Author::create(['name' => 'Dewi Pusspita,Niawati', 'singkatan' => 'PUS']);
Author::create(['name' => 'Dhani yudhiantoro', 'singkatan' => 'YUD']);
Author::create(['name' => 'Dharudin Mashud', 'singkatan' => 'MAS']);
Author::create(['name' => 'Diah Erna Triningsih', 'singkatan' => 'TRI']);
Author::create(['name' => 'Diah Erna triningsih, S.Pd.', 'singkatan' => 'TRI']);
Author::create(['name' => 'Dian Anggraeny', 'singkatan' => 'ANG']);
Author::create(['name' => 'dian kusuma suci,S.pd', 'singkatan' => 'SUC']);
Author::create(['name' => 'Diana Napitulu', 'singkatan' => 'NAP']);
Author::create(['name' => 'Didik H. Pambudi', 'singkatan' => 'PAM']);
Author::create(['name' => 'Dieter Beutelstahil', 'singkatan' => 'BEU']);
Author::create(['name' => 'Dijana plut, Ljiljana Marinkovic', 'singkatan' => 'PLU']);
Author::create(['name' => 'Dinas Pendidikan', 'singkatan' => 'PEN']);
Author::create(['name' => 'Dini afriyani', 'singkatan' => 'AFR']);
Author::create(['name' => 'Direktorat Jenderal Minyak dan Gas Bumi', 'singkatan' => 'BUM']);
Author::create(['name' => 'Djajasukma Tjahjadi', 'singkatan' => 'TJA']);
Author::create(['name' => 'Djohar Muzaki dkk', 'singkatan' => 'MUZ']);
Author::create(['name' => 'Djoko Darmawan', 'singkatan' => 'DJO']);
Author::create(['name' => 'Djunaidi Dwi P. A., M.Si.', 'singkatan' => 'DWI']);
Author::create(['name' => 'Dody Hidayat', 'singkatan' => 'HID']);
Author::create(['name' => 'Doni Koesoema', 'singkatan' => 'KOE']);
Author::create(['name' => 'Dr Achmad Juntika Nurihsan, M.Pd', 'singkatan' => 'NUR']);
Author::create(['name' => 'Dr Dewi Motik Pramono, M.Si', 'singkatan' => 'PRA']);
Author::create(['name' => 'Dr muhammad Bin"Abdullah As sahim', 'singkatan' => 'SAH']);
Author::create(['name' => 'Dr Sis Heyster', 'singkatan' => 'HEY']);
Author::create(['name' => 'Dr. Achmad Juntika Nurihsan, M.Pd.', 'singkatan' => 'JUN']);
Author::create(['name' => 'Dr. Asep Saeful Muhtadi, M.A', 'singkatan' => 'SAE']);
Author::create(['name' => 'Dr. Dasim Budimansyah, M,Si', 'singkatan' => 'BUD']);
Author::create(['name' => 'Dr. Dasim Budimansyah, M.Si', 'singkatan' => 'BUD']);
Author::create(['name' => 'Dr. Djamat Samosir, SH.M.H', 'singkatan' => 'SAM']);
Author::create(['name' => 'DR. H. Kabul Budiyono, M.Si', 'singkatan' => 'BUD']);
Author::create(['name' => 'Dr. H. Saaparudin, M.Sc', 'singkatan' => 'SAP']);
Author::create(['name' => 'Dr. Hermawan Sulistyo,Dkk', 'singkatan' => 'SUL']);
Author::create(['name' => 'Dr. Nana Herdiana Abdurahmanm S.E, AK, M.M', 'singkatan' => 'HER']);
Author::create(['name' => 'Dr. Reniati, S.E, M.Si', 'singkatan' => 'REN']);
Author::create(['name' => 'Dr. Sayyid Al Jumaili', 'singkatan' => 'JUM']);
Author::create(['name' => 'Dr. Sembodo Ardi Widodo', 'singkatan' => 'WID']);
Author::create(['name' => 'dr. Subagyo Partodiharjo', 'singkatan' => 'PAR']);
Author::create(['name' => 'Dr. Suparman Sumahamijaya, MA, SC.AK', 'singkatan' => 'SUM']);
Author::create(['name' => 'Dr. Syaiful sagala. M.pd', 'singkatan' => 'SAG']);
Author::create(['name' => 'dr. Widharto', 'singkatan' => 'WID']);
Author::create(['name' => 'Dr. Widodo Budiharto', 'singkatan' => 'BUD']);
Author::create(['name' => 'Dr. Y Sutiono Supinto', 'singkatan' => 'SUP']);
Author::create(['name' => 'Dr.D.J. Schwartz', 'singkatan' => 'SCH']);
Author::create(['name' => 'Dr.David fairbairn,dkk', 'singkatan' => 'FAI']);
Author::create(['name' => 'Dr.Endang Soenarya', 'singkatan' => 'SOE']);
Author::create(['name' => 'dr.Fella Karenina Susanti', 'singkatan' => 'SUS']);
Author::create(['name' => 'Dr.H.kabul budiyono,M.si', 'singkatan' => 'BUD']);
Author::create(['name' => 'Dr.Harlina Pribadi', 'singkatan' => 'PRI']);
Author::create(['name' => 'Dr.Harlina Pribadi,S.K.M,Dkk', 'singkatan' => 'PRI']);
Author::create(['name' => 'Dr.Idris Mandang,Msi,dkk', 'singkatan' => 'MAN']);
Author::create(['name' => 'Dr.Ir. Singgih Wibowo, M.S', 'singkatan' => 'WIB']);
Author::create(['name' => 'dr.lydia Harlina Martono,S.K.M. Dkk', 'singkatan' => 'MAR']);
Author::create(['name' => 'Dr.Mugni Baharuddin, SH,MM', 'singkatan' => 'BAH']);
Author::create(['name' => 'DR.R Kunjana Rahardi,M.HUM', 'singkatan' => 'MOE']);
Author::create(['name' => 'DR.Vincentinus Darmin', 'singkatan' => 'VIN']);
Author::create(['name' => 'Dra Rizqi Auliana, M.Kes', 'singkatan' => 'AUL']);
Author::create(['name' => 'Dra. Adriani Rilda,Dkk', 'singkatan' => 'RIL']);
Author::create(['name' => 'Dra. Endang Barigina', 'singkatan' => 'BAR']);
Author::create(['name' => 'Dra. Endang sadbudhy Rahayu, MBA, i made Nuryata,S.Pd, M.Pd', 'singkatan' => 'RAH']);
Author::create(['name' => 'Dra. Endang Sadbudhy rahayu, MBA,Dkk', 'singkatan' => 'SAH']);
Author::create(['name' => 'Dra. Marwanti.M. Pd', 'singkatan' => 'MAR']);
Author::create(['name' => 'Dra. Siti Djuwariyah, Dkk', 'singkatan' => 'DJU']);
Author::create(['name' => 'Dra. Siti Juariyah Suparlan, Drs.Rochani', 'singkatan' => 'SUP']);
Author::create(['name' => 'Dra. Yeyen Maryani', 'singkatan' => 'MAR']);
Author::create(['name' => 'Dra.Endang Sadbudhy Rahayu.MBA', 'singkatan' => 'RAH']);
Author::create(['name' => 'Dra.Rella Turella', 'singkatan' => 'TUR']);
Author::create(['name' => 'Dra.S.H. Lastyawati, Drs. Aris Nugroho', 'singkatan' => 'KAS']);
Author::create(['name' => 'Dra.S.H. Lastyawati, Drs. Aris Nugroho', 'singkatan' => 'LAS']);
Author::create(['name' => 'Drs ahmad Roy Handy Yoss', 'singkatan' => 'YOS']);
Author::create(['name' => 'Drs Daryanto', 'singkatan' => 'DAR']);
Author::create(['name' => 'Drs Edy Supriyadi', 'singkatan' => 'SUP']);
Author::create(['name' => 'Drs Fathuddin S.I.P', 'singkatan' => 'FAT']);
Author::create(['name' => 'Drs I Nyaman suaka', 'singkatan' => 'SUA']);
Author::create(['name' => 'Drs Idris Mandang,Dkk', 'singkatan' => 'MAN']);
Author::create(['name' => 'Drs Indra Jaya Nauman', 'singkatan' => 'NAU']);
Author::create(['name' => 'Drs Komalasari', 'singkatan' => 'KOM']);
Author::create(['name' => 'Drs M Aries Muthahar', 'singkatan' => 'MUT']);
Author::create(['name' => 'Drs Mafrukhi,M,Pd.Wahono,Spd,Dkk', 'singkatan' => 'MAF']);
Author::create(['name' => 'Drs Margiono,M.Pd. Dkk', 'singkatan' => 'MAR']);
Author::create(['name' => 'Drs Muh sugiarto Msi, Ismudi Dkk', 'singkatan' => 'SUG']);
Author::create(['name' => 'Drs Muhammad saleh', 'singkatan' => 'SAL']);
Author::create(['name' => 'Drs Najamuddin', 'singkatan' => 'NAJ']);
Author::create(['name' => 'Drs Yovinus', 'singkatan' => 'YOV']);
Author::create(['name' => 'Drs, T.May Rudy,SH.,MIR.,M.Sc.', 'singkatan' => 'RUD']);
Author::create(['name' => 'Drs. Muhammad Yani, M.Sc.Ed', 'singkatan' => 'YAN']);
Author::create(['name' => 'Drs. A Ari Dartoyo, M.Eng', 'singkatan' => 'ARI']);
Author::create(['name' => 'Drs. Agus Supriyanto', 'singkatan' => 'SUP']);
Author::create(['name' => 'Drs. Amrin Imran', 'singkatan' => 'IMR']);
Author::create(['name' => 'Drs. Bambang Puji Raharjo', 'singkatan' => 'PUJ']);
Author::create(['name' => 'Drs. Chotib, Drs.H.M.Dzuli,Dkk', 'singkatan' => 'CHO']);
Author::create(['name' => 'Drs. Daryanto', 'singkatan' => 'DAR']);
Author::create(['name' => 'Drs. Dedi Supriadi Idris', 'singkatan' => 'IDR']);
Author::create(['name' => 'Drs. E. Juhana Wijaya', 'singkatan' => 'WIJ']);
Author::create(['name' => 'Drs. Edi trinugroho', 'singkatan' => 'TRI']);
Author::create(['name' => 'Drs. Fatchur Rochman AR', 'singkatan' => 'FAT']);
Author::create(['name' => 'Drs. Gerard Termorshuizen', 'singkatan' => 'TER']);
Author::create(['name' => 'Drs. H. Achmad Amins, MM', 'singkatan' => 'AMI']);
Author::create(['name' => 'Drs. H. Hadiwijaya,DKK', 'singkatan' => 'HAD']);
Author::create(['name' => 'Drs. H. Rustamaji, M.Pd, Sular Badaruddin, S.Pd.', 'singkatan' => 'RUS']);
Author::create(['name' => 'Drs. H. Rustamaji, M.Pd.', 'singkatan' => 'RUS']);
Author::create(['name' => 'Drs. Imam Suhardiman', 'singkatan' => 'SUH']);
Author::create(['name' => 'Drs. Jaka Warsihna, M.Si DKK', 'singkatan' => 'WAR']);
Author::create(['name' => 'Drs. Joko Untoro', 'singkatan' => 'UNT']);
Author::create(['name' => 'Drs. Juhana Wijaya', 'singkatan' => 'WIJ']);
Author::create(['name' => 'Drs. Jumbadi, M.Pd', 'singkatan' => 'JUM']);
Author::create(['name' => 'Drs. Jumbadi.M.Pd', 'singkatan' => 'JUM']);
Author::create(['name' => 'Drs. M. Manullang', 'singkatan' => 'MAN']);
Author::create(['name' => 'Drs. Ma\'ruf Misbah, Drs. Ja\'far Sanusi, Ust. Abdullah Qusyairi M', 'singkatan' => 'MIS']);
Author::create(['name' => 'Drs. Maman Abdurahman, M.Pd', 'singkatan' => 'ABD']);
Author::create(['name' => 'Drs. Mardiyatmo, dkk', 'singkatan' => 'MAR']);
Author::create(['name' => 'Drs. Mulyadi', 'singkatan' => 'MUL']);
Author::create(['name' => 'Drs. Pardi, M.Hum', 'singkatan' => 'PAR']);
Author::create(['name' => 'Drs. Roji', 'singkatan' => 'ROJ']);
Author::create(['name' => 'Drs. Slamet Sutrisni, M.Si', 'singkatan' => 'SUT']);
Author::create(['name' => 'Drs. Sunarrso', 'singkatan' => 'SUN']);
Author::create(['name' => 'Drs. Sunarrso, Ir. Sunarmasto,MT', 'singkatan' => 'SUN']);
Author::create(['name' => 'Drs. Suparman, S.S., M.Hum. Sri Hartatik, S.Pd.', 'singkatan' => 'SUP']);
Author::create(['name' => 'Drs. Wahyu Ms', 'singkatan' => 'WAH']);
Author::create(['name' => 'Drs. Wasty Soemanto, M. Pd', 'singkatan' => 'SOE']);
Author::create(['name' => 'Drs. Wita Sutrisno,M.Pd', 'singkatan' => 'SUT']);
Author::create(['name' => 'Drs.Asul Wiyanto', 'singkatan' => 'WIY']);
Author::create(['name' => 'Drs.B. Surya Subroto', 'singkatan' => 'SUB']);
Author::create(['name' => 'Drs.C.S.T. Kansil, D.H', 'singkatan' => 'KAN']);
Author::create(['name' => 'Drs.Djiko Purwanto.M.B.A', 'singkatan' => 'PUR']);
Author::create(['name' => 'Drs.E. Juhana Wijaya', 'singkatan' => 'WIJ']);
Author::create(['name' => 'Drs.H. Abdul aziz, M.A', 'singkatan' => 'AZI']);
Author::create(['name' => 'Drs.I.B Made Mertho', 'singkatan' => 'MER']);
Author::create(['name' => 'Drs.Istiono.MH', 'singkatan' => 'IST']);
Author::create(['name' => 'Drs.Margiono,M.Pd,Dkk', 'singkatan' => 'MAR']);
Author::create(['name' => 'Drs.Mukhamad Irman.MM,Dkk', 'singkatan' => 'IRM']);
Author::create(['name' => 'Drs.Priyanto Susiloadi,M.Si', 'singkatan' => 'SUS']);
Author::create(['name' => 'Drs.Suarga.M.Sc,M.Math.Ph.D', 'singkatan' => 'SUA']);
Author::create(['name' => 'Drs.Sunarrso', 'singkatan' => 'SUN']);
Author::create(['name' => 'Dwi Atmi Wahyu S.', 'singkatan' => 'ATM']);
Author::create(['name' => 'Dwi Nugroho Hidayanto', 'singkatan' => 'HID']);
Author::create(['name' => 'Dyah Sudarsi, S.E', 'singkatan' => 'SUD']);
Author::create(['name' => 'Dyayadi', 'singkatan' => 'DYA']);
Author::create(['name' => 'E. Juhana Wijaya', 'singkatan' => 'WIJ']);
Author::create(['name' => 'Eddy Soetrisno', 'singkatan' => 'SOE']);
Author::create(['name' => 'Edi S Mulyanta', 'singkatan' => 'MUL']);
Author::create(['name' => 'Edi S Mulyanta, S.Si', 'singkatan' => 'EDI']);
Author::create(['name' => 'Edi S.Mulyanta', 'singkatan' => 'MUL']);
Author::create(['name' => 'Edi S.Mulyanta.Retna Gunarsih', 'singkatan' => 'MUL']);
Author::create(['name' => 'Edi warsidi', 'singkatan' => 'WAR']);
Author::create(['name' => 'Edi.S, Retna Gunarsi', 'singkatan' => 'MUL']);
Author::create(['name' => 'Edwar Djamaris', 'singkatan' => 'DJA']);
Author::create(['name' => 'Edy Winarno ST, M.Eng, Ali Zaki & SmitDev Community', 'singkatan' => 'WIN']);
Author::create(['name' => 'Efisitetek.com', 'singkatan' => 'EFI']);
Author::create(['name' => 'Efriyani Djuwita', 'singkatan' => 'EFR']);
Author::create(['name' => 'Eka Murjianta, S.Pd', 'singkatan' => 'MUR']);
Author::create(['name' => 'Eko H,Setianto', 'singkatan' => 'SET']);
Author::create(['name' => 'Eko Indiyawan ( dan kawan")', 'singkatan' => 'IND']);
Author::create(['name' => 'Eko Priyo Utomo,ST', 'singkatan' => 'EKO']);
Author::create(['name' => 'Eko Priyo Utomo,ST', 'singkatan' => 'PRI']);
Author::create(['name' => 'Eko Sujatmiko', 'singkatan' => 'SUJ']);
Author::create(['name' => 'Eko Sujatmiko,S.Si', 'singkatan' => 'SUJ']);
Author::create(['name' => 'Elcom', 'singkatan' => 'ELC']);
Author::create(['name' => 'Eli Novitasari', 'singkatan' => 'NOV']);
Author::create(['name' => 'Elizabetth,Bauchner', 'singkatan' => 'ELI']);
Author::create(['name' => 'Elsabil Amadina', 'singkatan' => 'AMA']);
Author::create(['name' => 'Ema Wardana, Rahimsyah', 'singkatan' => 'WAR']);
Author::create(['name' => 'Emha Ainun Nadjib', 'singkatan' => 'NAD']);
Author::create(['name' => 'Endah Dumilah,DKK', 'singkatan' => 'DUM']);
Author::create(['name' => 'Endang Dwi Lestari', 'singkatan' => 'LES']);
Author::create(['name' => 'Endar Wismulyani', 'singkatan' => 'WIS']);
Author::create(['name' => 'Endar wismulyani,S.Pd', 'singkatan' => 'WIS']);
Author::create(['name' => 'Endi Suhendi Zan & Nelty Khairiyah', 'singkatan' => 'SUH']);
Author::create(['name' => 'Enget,dkk', 'singkatan' => 'ENG']);
Author::create(['name' => 'Engkos Kosasih', 'singkatan' => 'KOS']);
Author::create(['name' => 'Eni Anjaya', 'singkatan' => 'ANJ']);
Author::create(['name' => 'Eni Anjayani', 'singkatan' => 'ANJ']);
Author::create(['name' => 'Eni Anjayani, s.Si', 'singkatan' => 'ANJ']);
Author::create(['name' => 'Eni Anjayani,S.Si', 'singkatan' => 'ENJ']);
Author::create(['name' => 'Eni Muzazanah.S.Pd', 'singkatan' => 'MUZ']);
Author::create(['name' => 'Entin Sutinah, dkk', 'singkatan' => 'SUT']);
Author::create(['name' => 'Erbe Sentanu', 'singkatan' => 'SEN']);
Author::create(['name' => 'Eri, Kurniawan DKK', 'singkatan' => 'KUR']);
Author::create(['name' => 'Erich Von Daniken', 'singkatan' => 'VON']);
Author::create(['name' => 'Erma Yulistin', 'singkatan' => 'YUL']);
Author::create(['name' => 'Ermina Krismarsanti', 'singkatan' => 'KRI']);
Author::create(['name' => 'Erminawati', 'singkatan' => 'ERM']);
Author::create(['name' => 'Ernawati, Dewi Luvfiati, Mieke Miarsyah, Tia Mutiara', 'singkatan' => 'DEW']);
Author::create(['name' => 'Ernawati,dkk', 'singkatan' => 'ERN']);
Author::create(['name' => 'Erwin Adi Putranto', 'singkatan' => 'ADI']);
Author::create(['name' => 'Erwin Philipus', 'singkatan' => 'PHI']);
Author::create(['name' => 'Ery Hermawan', 'singkatan' => 'HER']);
Author::create(['name' => 'Es Pernyata', 'singkatan' => 'PER']);
Author::create(['name' => 'Esi Lahur', 'singkatan' => 'LAH']);
Author::create(['name' => 'Esparno', 'singkatan' => 'ESP']);
Author::create(['name' => 'Etty Sugiarti, S.Pd', 'singkatan' => 'SUG']);
Author::create(['name' => 'Euis honiatri', 'singkatan' => 'HON']);
Author::create(['name' => 'Euis Sulastri', 'singkatan' => 'SUL']);
Author::create(['name' => 'Fahd Djibran', 'singkatan' => 'DJI']);
Author::create(['name' => 'Fajar M.n', 'singkatan' => 'FAJ']);
Author::create(['name' => 'fajar Rachmawati', 'singkatan' => 'RAC']);
Author::create(['name' => 'Fajar Rachmawati', 'singkatan' => 'WAR']);
Author::create(['name' => 'farida Piji P', 'singkatan' => 'PIJ']);
Author::create(['name' => 'Farida puji p.', 'singkatan' => 'PUJ']);
Author::create(['name' => 'Fathansyah', 'singkatan' => 'FAT']);
Author::create(['name' => 'Feisal Ghozaly & HA. Sholeh Dimyathi', 'singkatan' => 'FEI']);
Author::create(['name' => 'Felix Y. Siauw', 'singkatan' => 'SIA']);
Author::create(['name' => 'Feri Kurniawan', 'singkatan' => 'KUR']);
Author::create(['name' => 'Ferli Zulhendi', 'singkatan' => 'ZUL']);
Author::create(['name' => 'Fermana', 'singkatan' => 'FER']);
Author::create(['name' => 'Fiki puspitasari', 'singkatan' => 'PUS']);
Author::create(['name' => 'Firrar Utdiartatmo', 'singkatan' => 'UTD']);
Author::create(['name' => 'Fitri nurhartati,dkk', 'singkatan' => 'NUR']);
Author::create(['name' => 'Fokusmedia', 'singkatan' => 'RED']);
Author::create(['name' => 'frans', 'singkatan' => 'FRA']);
Author::create(['name' => 'G. Purwanto & E. Sulasmi', 'singkatan' => 'PUR']);
Author::create(['name' => 'Gail Snyder', 'singkatan' => 'SNY']);
Author::create(['name' => 'Galih jati kuncomo', 'singkatan' => 'KUN']);
Author::create(['name' => 'ganesha operation', 'singkatan' => 'OPE']);
Author::create(['name' => 'Gatut Susanta, Hari Sutjahjo', 'singkatan' => 'SUS']);
Author::create(['name' => 'Genevieve De Becker', 'singkatan' => 'BEC']);
Author::create(['name' => 'Ginanjar Atmasubrata, S.Pd.', 'singkatan' => 'ATM']);
Author::create(['name' => 'Gintoro', 'singkatan' => 'GIN']);
Author::create(['name' => 'Giyarto', 'singkatan' => 'GIY']);
Author::create(['name' => 'Goenawan Mohamad', 'singkatan' => 'MOH']);
Author::create(['name' => 'gordon winch', 'singkatan' => 'WIN']);
Author::create(['name' => 'Gorys Keraf', 'singkatan' => 'KER']);
Author::create(['name' => 'Grahamesia Press', 'singkatan' => 'PRE']);
Author::create(['name' => 'Gregorius Agung', 'singkatan' => 'AGU']);
Author::create(['name' => 'Grenville kleiser', 'singkatan' => 'KLE']);
Author::create(['name' => 'Guiyeoni', 'singkatan' => 'GUI']);
Author::create(['name' => 'Gunadi', 'singkatan' => 'GUN']);
Author::create(['name' => 'Gusrina', 'singkatan' => 'GUS']);
Author::create(['name' => 'Gypsona Group Unhas', 'singkatan' => 'UNH']);
Author::create(['name' => 'H Atik sobari SH', 'singkatan' => 'SOB']);
Author::create(['name' => 'H. Sulaiman Rasjif', 'singkatan' => 'SUL']);
Author::create(['name' => 'H. Syaharie Jaang, SH, M.Si', 'singkatan' => 'JAA']);
Author::create(['name' => 'H.A Tabrani Rusyan', 'singkatan' => 'RUS']);
Author::create(['name' => 'H.M Zaenoeddin', 'singkatan' => 'ZAE']);
Author::create(['name' => 'H.M. Ridwan Tasa & Umar Vaturasi', 'singkatan' => 'TAS']);
Author::create(['name' => 'H.Subardi,Andri Setyawan', 'singkatan' => 'SUB']);
Author::create(['name' => 'H.supari Muslim', 'singkatan' => 'MUS']);
Author::create(['name' => 'H.Syaharie ja\'ah.SH.Msi', 'singkatan' => 'JA\'']);
Author::create(['name' => 'H.Zakaria Idris', 'singkatan' => 'IDR']);
Author::create(['name' => 'Habib Adnan, Spd', 'singkatan' => 'ADN']);
Author::create(['name' => 'Habiburrahman El Shirazy', 'singkatan' => 'SHI']);
Author::create(['name' => 'Hal Marcovitz', 'singkatan' => 'MAR']);
Author::create(['name' => 'halimi Hadibrata, S.pd', 'singkatan' => 'HAD']);
Author::create(['name' => 'Hamdan W Tarerasi', 'singkatan' => 'TAR']);
Author::create(['name' => 'Hamid Jabbar', 'singkatan' => 'JAB']);
Author::create(['name' => 'Hamsi Hamzah', 'singkatan' => 'HAM']);
Author::create(['name' => 'Hani\'ah', 'singkatan' => 'HAN']);
Author::create(['name' => 'Hardana & Ino Irvanto', 'singkatan' => 'HAR']);
Author::create(['name' => 'Harijanto Pribadi', 'singkatan' => 'PRI']);
Author::create(['name' => 'Harimurti WS', 'singkatan' => 'HAR']);
Author::create(['name' => 'Harry D Fauzi', 'singkatan' => 'FAU']);
Author::create(['name' => 'Harry D Fauzi & Yadi Mulyadi', 'singkatan' => 'FAU']);
Author::create(['name' => 'Harsanto', 'singkatan' => 'HAR']);
Author::create(['name' => 'Hartojo andang', 'singkatan' => 'AND']);
Author::create(['name' => 'Harudjati Purworo', 'singkatan' => 'PUR']);
Author::create(['name' => 'Hasan bin Ahmad Hammam', 'singkatan' => 'AHM']);
Author::create(['name' => 'Hearter Amery', 'singkatan' => 'AME']);
Author::create(['name' => 'Heldin Manurung', 'singkatan' => 'MAN']);
Author::create(['name' => 'Helena Olii', 'singkatan' => 'OLI']);
Author::create(['name' => 'helmi hadibarata, S.Pd', 'singkatan' => 'HAN']);
Author::create(['name' => 'Hendi F. Isnaeni', 'singkatan' => 'ISN']);
Author::create(['name' => 'Hendi Hendratman, ST. Gema Arifrahara,S.Sn.', 'singkatan' => 'HEN']);
Author::create(['name' => 'HendiHendratman, ST & Robby ST', 'singkatan' => 'HEN']);
Author::create(['name' => 'Hendra Akbar', 'singkatan' => 'AKB']);
Author::create(['name' => 'Hendra M saregih, Impran Hunayan, Nurdin muhammad', 'singkatan' => 'SAR']);
Author::create(['name' => 'Hendrayudi', 'singkatan' => 'HEN']);
Author::create(['name' => 'Hendro', 'singkatan' => 'HEN']);
Author::create(['name' => 'Hendy Hendratman', 'singkatan' => 'HEN']);
Author::create(['name' => 'Hendy Hudaya', 'singkatan' => 'HEN']);
Author::create(['name' => 'Heni A.Puspitosari', 'singkatan' => 'PUS']);
Author::create(['name' => 'Her Suganda', 'singkatan' => 'SUG']);
Author::create(['name' => 'Heri Nuryanto', 'singkatan' => 'NUR']);
Author::create(['name' => 'Herman As salam', 'singkatan' => 'SAL']);
Author::create(['name' => 'Herman Praktikto', 'singkatan' => 'PRA']);
Author::create(['name' => 'Herni Kusantati,dkk', 'singkatan' => 'KUS']);
Author::create(['name' => 'Huang Hua,Sugeng Aryanto', 'singkatan' => 'HUA']);
Author::create(['name' => 'Humaira \' Bintu Bekti', 'singkatan' => 'HUM']);
Author::create(['name' => 'Humaira\' Bintu Bekti', 'singkatan' => 'BIN']);
Author::create(['name' => 'Hunum Sofnas S.pd', 'singkatan' => 'SOF']);
Author::create(['name' => 'Husanto & Thomas', 'singkatan' => 'HUS']);
Author::create(['name' => 'I wayan Badrika', 'singkatan' => 'BAD']);
Author::create(['name' => 'I Wayan Dibia, dkk', 'singkatan' => 'DIB']);
Author::create(['name' => 'I.S. Warsanto', 'singkatan' => 'WAR']);
Author::create(['name' => 'Ibnu Hamid', 'singkatan' => 'HAM']);
Author::create(['name' => 'ichwan fayzi,Lc', 'singkatan' => 'FAY']);
Author::create(['name' => 'Ida Listyarini Handoyo,S.Si.,M.Si', 'singkatan' => 'HAN']);
Author::create(['name' => 'Ida Maharani', 'singkatan' => 'MAH']);
Author::create(['name' => 'Idi Supono', 'singkatan' => 'SUP']);
Author::create(['name' => 'Ignas', 'singkatan' => 'IGN']);
Author::create(['name' => 'Ika Muliawati', 'singkatan' => 'MUL']);
Author::create(['name' => 'Ilana Tan', 'singkatan' => 'TAN']);
Author::create(['name' => 'Ilman Soleh', 'singkatan' => 'SOL']);
Author::create(['name' => 'Ilmu Hayat', 'singkatan' => 'ILM']);
Author::create(['name' => 'Imadi', 'singkatan' => 'IMA']);
Author::create(['name' => 'Imam Budi Utomo & TIM', 'singkatan' => 'BUD']);
Author::create(['name' => 'Imam Cartealy', 'singkatan' => 'CAR']);
Author::create(['name' => 'imam haryanto, budi raharjo', 'singkatan' => 'HAR']);
Author::create(['name' => 'Imam Himawan', 'singkatan' => 'HIM']);
Author::create(['name' => 'Imam Machali', 'singkatan' => 'MAC']);
Author::create(['name' => 'Imam Musbikin', 'singkatan' => 'MUS']);
Author::create(['name' => 'Imam Rofi\'ie', 'singkatan' => 'ROF']);
Author::create(['name' => 'Imam Syaukani', 'singkatan' => 'SYA']);
Author::create(['name' => 'Iman Budhi Santosa', 'singkatan' => 'SAN']);
Author::create(['name' => 'Imzen Sitorus', 'singkatan' => 'IMZ']);
Author::create(['name' => 'Indah Setyowati', 'singkatan' => 'SET']);
Author::create(['name' => 'Indra Herlambang', 'singkatan' => 'HER']);
Author::create(['name' => 'Indri yuli astuti', 'singkatan' => 'AST']);
Author::create(['name' => 'Intan Pariwara', 'singkatan' => 'PAR']);
Author::create(['name' => 'Ippho Santosa', 'singkatan' => 'SAN']);
Author::create(['name' => 'Ippho Santoso', 'singkatan' => 'SAN']);
Author::create(['name' => 'Iqra Al Firdaus,dkk', 'singkatan' => 'FIR']);
Author::create(['name' => 'Ir Gusrina', 'singkatan' => 'GUS']);
Author::create(['name' => 'Ir. Pandapotan Sianipar', 'singkatan' => 'SIA']);
Author::create(['name' => 'Ir. Rudiyanto,M.A', 'singkatan' => 'RUD']);
Author::create(['name' => 'Ir.siswadi, M.P', 'singkatan' => 'SIS']);
Author::create(['name' => 'Ir.Suryanto Tabrani', 'singkatan' => 'SUR']);
Author::create(['name' => 'Ira Wijayanti', 'singkatan' => 'WIJ']);
Author::create(['name' => 'Irawan', 'singkatan' => 'IRA']);
Author::create(['name' => 'Irman Maulana', 'singkatan' => 'MAU']);
Author::create(['name' => 'Irwan H prasetya', 'singkatan' => 'PRA']);
Author::create(['name' => 'Isak Rickyanto ST', 'singkatan' => 'RIC']);
Author::create(['name' => 'isbedy Stiawan Z.s', 'singkatan' => 'STI']);
Author::create(['name' => 'Ismail Maharimin', 'singkatan' => 'MAH']);
Author::create(['name' => 'Ismail pamungkas', 'singkatan' => 'PAM']);
Author::create(['name' => 'isnu Murdewa, S.Pd Dkk', 'singkatan' => 'MUR']);
Author::create(['name' => 'Isroi', 'singkatan' => 'ISR']);
Author::create(['name' => 'Iswanto', 'singkatan' => 'ISW']);
Author::create(['name' => 'Ita Kristi', 'singkatan' => 'KRI']);
Author::create(['name' => 'Iwan Heri Santoso, S.Pd', 'singkatan' => 'SAN']);
Author::create(['name' => 'iwuk p', 'singkatan' => 'IWU']);
Author::create(['name' => 'J.Douglas Faires', 'singkatan' => 'FAI']);
Author::create(['name' => 'Jaenudin,ST', 'singkatan' => 'JAE']);
Author::create(['name' => 'Jaja Jamaludin Malik', 'singkatan' => 'JAM']);
Author::create(['name' => 'Jaka sunardi, Rustamaji', 'singkatan' => 'SUN']);
Author::create(['name' => 'Jake allsop', 'singkatan' => 'ALL']);
Author::create(['name' => 'Jalius jama,dkk', 'singkatan' => 'JAM']);
Author::create(['name' => 'Jamal D Rahman', 'singkatan' => 'RAH']);
Author::create(['name' => 'Jamia Jabar', 'singkatan' => 'JAB']);
Author::create(['name' => 'Janner Simarmata', 'singkatan' => 'SIM']);
Author::create(['name' => 'Jarot Setyaji', 'singkatan' => 'JAR']);
Author::create(['name' => 'Jasakom', 'singkatan' => 'JAS']);
Author::create(['name' => 'Jasmadi', 'singkatan' => 'JAS']);
Author::create(['name' => 'Jasman', 'singkatan' => 'JAS']);
Author::create(['name' => 'Jayan', 'singkatan' => 'JAY']);
Author::create(['name' => 'jean otto ford', 'singkatan' => 'FOR']);
Author::create(['name' => 'Jennifer Justice', 'singkatan' => 'JUS']);
Author::create(['name' => 'Jhon Shors', 'singkatan' => 'SHO']);
Author::create(['name' => 'Jim Brown, Ph. D', 'singkatan' => 'BRO']);
Author::create(['name' => 'Jim Geier', 'singkatan' => 'GEI']);
Author::create(['name' => 'Jim Geier', 'singkatan' => 'JIM']);
Author::create(['name' => 'jim geler', 'singkatan' => 'GEL']);
Author::create(['name' => 'Jogiyanto H.M', 'singkatan' => 'JOG']);
Author::create(['name' => 'Johan Syah Balham', 'singkatan' => 'BAL']);
Author::create(['name' => 'Johansyah Balham', 'singkatan' => 'BAL']);
Author::create(['name' => 'john Bessett', 'singkatan' => 'BES']);
Author::create(['name' => 'John Farndon', 'singkatan' => 'FAR']);
Author::create(['name' => 'John H,Edgette, PSYD & Tim Rawon, MSw', 'singkatan' => 'EDG']);
Author::create(['name' => 'john O.E.Clark', 'singkatan' => 'CLA']);
Author::create(['name' => 'Joko Budi Santoso', 'singkatan' => 'SAN']);
Author::create(['name' => 'Joko Pamungkas', 'singkatan' => 'PAM']);
Author::create(['name' => 'Joko Widiyatmoko', 'singkatan' => 'WID']);
Author::create(['name' => 'Joko Widiyatmoko,Dkk', 'singkatan' => 'WID']);
Author::create(['name' => 'Jon Oliver', 'singkatan' => 'OLI']);
Author::create(['name' => 'Joni Aria Dinata', 'singkatan' => 'DIN']);
Author::create(['name' => 'Joni Lennon', 'singkatan' => 'LEN']);
Author::create(['name' => 'Joto Soenarto', 'singkatan' => 'soe']);
Author::create(['name' => 'Jubilee Enterprise', 'singkatan' => 'ENT']);
Author::create(['name' => 'Jubilee Enterprise', 'singkatan' => 'JUB']);
Author::create(['name' => 'Junindar, MVP VB.NET', 'singkatan' => 'JUN']);
Author::create(['name' => 'Jusran safano', 'singkatan' => 'SAF']);
Author::create(['name' => 'K. Wardiyatmoko', 'singkatan' => 'WAR']);
Author::create(['name' => 'K.Usman', 'singkatan' => 'USM']);
Author::create(['name' => 'K.Zainuri Ihsan, S.AG', 'singkatan' => 'HIS']);
Author::create(['name' => 'Kantor mentri negara urusan koperasi usaha kecil dan menengah R.I', 'singkatan' => 'KKUKM']);
Author::create(['name' => 'Karmila', 'singkatan' => 'KAR']);
Author::create(['name' => 'Kasiman Peranginangsih', 'singkatan' => 'PER']);
Author::create(['name' => 'Kasmina, dkk', 'singkatan' => 'KAS']);
Author::create(['name' => 'Kasmir, S.E.,M.M', 'singkatan' => 'KAS']);
Author::create(['name' => 'Kate Bradshaw', 'singkatan' => 'BRA']);
Author::create(['name' => 'Kelaswara setiyadi & Kurnia ayu rahmawati', 'singkatan' => 'SET']);
Author::create(['name' => 'Kementerian Koperasi dan UKM Deputi Bidang Pengembangan SDM', 'singkatan' => 'KKUKBPS']);
Author::create(['name' => 'Kementerian Koperasi dan Usaha Kecil dan Menengah Republik Indonesia', 'singkatan' => '']);
Author::create(['name' => 'Kementrian Indonesia', 'singkatan' => 'IND']);
Author::create(['name' => 'Kementrian koperasi dan usaha kecil dan menengah repiblok indonesia', 'singkatan' => 'KKUKM']);
Author::create(['name' => 'Kementrian Pendidikan dan Kebudayaan', 'singkatan' => 'PEN']);
Author::create(['name' => 'kendra wenzel, Rene wanzel', 'singkatan' => 'WEN']);
Author::create(['name' => 'Keni Andewi', 'singkatan' => 'AND']);
Author::create(['name' => 'keven A. Prusak', 'singkatan' => 'PRU']);
Author::create(['name' => 'KH.A Mustofa Bisri', 'singkatan' => 'BIS']);
Author::create(['name' => 'KH.Abdullah Zaki Al Kaaf', 'singkatan' => 'KAA']);
Author::create(['name' => 'Khabib Basori', 'singkatan' => 'BAS']);
Author::create(['name' => 'Khabib Basori, Nur Khoiro Umatin', 'singkatan' => 'BAS']);
Author::create(['name' => 'Khalil Gibran', 'singkatan' => 'GIB']);
Author::create(['name' => 'Khoerussalim Ikhs', 'singkatan' => 'IKH']);
Author::create(['name' => 'Khrisna Pabichara', 'singkatan' => 'PAB']);
Author::create(['name' => 'Khusnul khotimah, Nining khasanah', 'singkatan' => 'KHO']);
Author::create(['name' => 'Kiki Zakiah', 'singkatan' => 'ZAK']);
Author::create(['name' => 'Kinkin Suartini', 'singkatan' => 'SUA']);
Author::create(['name' => 'Kok Yung', 'singkatan' => 'YUN']);
Author::create(['name' => 'Kokom komalasari', 'singkatan' => 'KOM']);
Author::create(['name' => 'Kokom Kumalasari', 'singkatan' => 'KUM']);
Author::create(['name' => 'Kompol Djoko Tjahyono, S.H., S.I.K.', 'singkatan' => 'TJA']);
Author::create(['name' => 'Korrie Layun Rampan', 'singkatan' => 'LAY']);
Author::create(['name' => 'Korrie Layun Rampan', 'singkatan' => 'RAM']);
Author::create(['name' => 'Kosmina,Toali, suhendra.Dkk', 'singkatan' => 'KOS']);
Author::create(['name' => 'Kustanto & Daniel T Saputro', 'singkatan' => 'KUS']);
Author::create(['name' => 'L.M Sitorus', 'singkatan' => 'SIT']);
Author::create(['name' => 'Lagiun veteran markas cabang kota tarakan', 'singkatan' => 'LVMC']);
Author::create(['name' => 'Laila S, Chudari', 'singkatan' => 'CHU']);
Author::create(['name' => 'Lambang subagyo,Dkk', 'singkatan' => 'SUB']);
Author::create(['name' => 'Lauren Oliver', 'singkatan' => 'OLI']);
Author::create(['name' => 'Lea Erawati budiman', 'singkatan' => 'BUD']);
Author::create(['name' => 'Leo agung, Dwi Ari L', 'singkatan' => 'AGU']);
Author::create(['name' => 'Lexie Xu', 'singkatan' => 'LEX']);
Author::create(['name' => 'LH. Santoso', 'singkatan' => 'SAN']);
Author::create(['name' => 'Lingga Wardhana', 'singkatan' => 'WAR']);
Author::create(['name' => 'Lisa Magloff', 'singkatan' => 'MAG']);
Author::create(['name' => 'Louis Gottschalk', 'singkatan' => 'GOT']);
Author::create(['name' => 'LPK EDHA', 'singkatan' => 'EDH']);
Author::create(['name' => 'Lucas Setyaputra', 'singkatan' => 'SET']);
Author::create(['name' => 'lukman hakim', 'singkatan' => 'HAK']);
Author::create(['name' => 'M Sadyi Masun', 'singkatan' => 'MAS']);
Author::create(['name' => 'M sofyan', 'singkatan' => 'SOF']);
Author::create(['name' => 'M. Amir P. Ali', 'singkatan' => 'AMI']);
Author::create(['name' => 'M. Ghufran H. Kordi K.', 'singkatan' => 'KOR']);
Author::create(['name' => 'M. Idris AS,Hafidotul Hasanah, M. Ismail', 'singkatan' => 'ISM']);
Author::create(['name' => 'M. Ihsan Fauzi, S.Si.', 'singkatan' => 'FAU']);
Author::create(['name' => 'M. Jamiluddin Ritonga', 'singkatan' => 'RIT']);
Author::create(['name' => 'M. Purwati', 'singkatan' => 'PUR']);
Author::create(['name' => 'M. Sadyi Masun', 'singkatan' => 'MAS']);
Author::create(['name' => 'M. Syafii', 'singkatan' => 'SYA']);
Author::create(['name' => 'M. Thobroni', 'singkatan' => 'THO']);
Author::create(['name' => 'M. yahya Arwiyah & TIM', 'singkatan' => 'YAH']);
Author::create(['name' => 'M. Zamakh Syarifani', 'singkatan' => 'SYA']);
Author::create(['name' => 'M.A. Desky', 'singkatan' => 'DES']);
Author::create(['name' => 'M.Amir P.ali', 'singkatan' => 'ALI']);
Author::create(['name' => 'M.Azrul Tanjung, dkk', 'singkatan' => 'TAN']);
Author::create(['name' => 'M.G Hesti Puji Rastuti', 'singkatan' => 'RAS']);
Author::create(['name' => 'M.G.Hesti Puji Rastuti', 'singkatan' => 'RAS']);
Author::create(['name' => 'M.Ihsan Fauzi, S.Si', 'singkatan' => 'FAU']);
Author::create(['name' => 'M.Ihsan Fauzi,S.Si', 'singkatan' => 'FAU']);
Author::create(['name' => 'M.Ikhsan Fauzi,S.Si', 'singkatan' => 'FAU']);
Author::create(['name' => 'M.K alamsyah Erna Sunarti', 'singkatan' => 'SUN']);
Author::create(['name' => 'M.Nasikin', 'singkatan' => 'NAS']);
Author::create(['name' => 'M.Purwati,Dkk', 'singkatan' => 'PUR']);
Author::create(['name' => 'M.Rudyanto Arief', 'singkatan' => 'ARI']);
Author::create(['name' => 'M.Suyanto', 'singkatan' => 'SUY']);
Author::create(['name' => 'M.Taufiq', 'singkatan' => 'TAU']);
Author::create(['name' => 'M.Th.kristianti', 'singkatan' => 'KRIS']);
Author::create(['name' => 'M.TH.Kristiati', 'singkatan' => '']);
Author::create(['name' => 'M.TH.Kristiati', 'singkatan' => 'KRI']);
Author::create(['name' => 'M.Thabrani', 'singkatan' => 'THA']);
Author::create(['name' => 'M.Winanto Ajie P H', 'singkatan' => 'AJI']);
Author::create(['name' => 'Madcoms', 'singkatan' => 'MAD']);
Author::create(['name' => 'Madcoms Madiun', 'singkatan' => 'MAD']);
Author::create(['name' => 'Maesita Maharani', 'singkatan' => 'MAH']);
Author::create(['name' => 'Magdalia Alfan, Nano Nurliana, Dkk', 'singkatan' => 'ALF']);
Author::create(['name' => 'Mahfid Ikhwan', 'singkatan' => 'IKH']);
Author::create(['name' => 'Mahmud Jauhari Ali', 'singkatan' => 'JAU']);
Author::create(['name' => 'Majalah Muslimah', 'singkatan' => 'MUS']);
Author::create(['name' => 'Maman Sumantri', 'singkatan' => 'SUM']);
Author::create(['name' => 'Mandar maju', 'singkatan' => 'MAN']);
Author::create(['name' => 'Mardan Tappang, Tammi Prastowo', 'singkatan' => 'TAP']);
Author::create(['name' => 'Mardiana wati', 'singkatan' => 'WAT']);
Author::create(['name' => 'Margaretha Mega Natalia, DKK', 'singkatan' => 'NAT']);
Author::create(['name' => 'Maria Regina Dyah Pramesti,Dkk', 'singkatan' => 'PRA']);
Author::create(['name' => 'Mariyono San Dwi, S.Pd.', 'singkatan' => 'DWI']);
Author::create(['name' => 'Mark mysnyk, Barry Davis, Brooks simpson', 'singkatan' => 'MYS']);
Author::create(['name' => 'Marlinda hayati', 'singkatan' => 'HAY']);
Author::create(['name' => 'Marlon Leong', 'singkatan' => 'LEO']);
Author::create(['name' => 'Marlon Peranginangin, N,Otorino,Dkk', 'singkatan' => 'PER']);
Author::create(['name' => 'Marta Yuliani', 'singkatan' => 'YUL']);
Author::create(['name' => 'Marthen Kanginan', 'singkatan' => 'KAN']);
Author::create(['name' => 'Mary Jane Sterling', 'singkatan' => 'STE']);
Author::create(['name' => 'Masdar Zainal', 'singkatan' => 'MAS']);
Author::create(['name' => 'Mashuri, Dkk', 'singkatan' => 'MAS']);
Author::create(['name' => 'Masykur Arif', 'singkatan' => 'ARI']);
Author::create(['name' => 'Matilda Gollon', 'singkatan' => 'GOL']);
Author::create(['name' => 'Matius Tomy Suryadi', 'singkatan' => 'MAT']);
Author::create(['name' => 'Matius Tomy Suryadi', 'singkatan' => 'TOM']);
Author::create(['name' => 'Matthew Housden', 'singkatan' => 'HOU']);
Author::create(['name' => 'Maulana Firdaus', 'singkatan' => 'FIR']);
Author::create(['name' => 'Medhy Aginta', 'singkatan' => 'AGI']);
Author::create(['name' => 'Mega fibrianti', 'singkatan' => 'FIB']);
Author::create(['name' => 'Meidiana F', 'singkatan' => 'MEI']);
Author::create(['name' => 'Merari Siregar', 'singkatan' => 'SIR']);
Author::create(['name' => 'Michael Purba', 'singkatan' => 'PUR']);
Author::create(['name' => 'Michael R. Wijela', 'singkatan' => 'WIJ']);
Author::create(['name' => 'Mico Pardosi', 'singkatan' => 'PAR']);
Author::create(['name' => 'Miftah Thoha', 'singkatan' => 'THO']);
Author::create(['name' => 'Miftahul Asror', 'singkatan' => 'ASR']);
Author::create(['name' => 'Miftahul Jannah S.Sn', 'singkatan' => 'JAN']);
Author::create(['name' => 'Mike FlyNN', 'singkatan' => 'FLY']);
Author::create(['name' => 'Mike Rini Sutikno & windya Novita', 'singkatan' => 'RIN']);
Author::create(['name' => 'Milman & Halkias', 'singkatan' => 'MIL']);
Author::create(['name' => 'Minto', 'singkatan' => 'MIN']);
Author::create(['name' => 'Miriam Edwards', 'singkatan' => 'EDW']);
Author::create(['name' => 'Mirma Respati', 'singkatan' => 'RES']);
Author::create(['name' => 'Misbah Yusa Biran', 'singkatan' => 'BIR']);
Author::create(['name' => 'Moch. Faisal Salam,SH., MH.', 'singkatan' => 'SAL']);
Author::create(['name' => 'Moh. Kusnadi', 'singkatan' => 'KUS']);
Author::create(['name' => 'Moh. Rofii Adji Sayekti', 'singkatan' => 'SAY']);
Author::create(['name' => 'Mokh. Syaiful Bakhri', 'singkatan' => 'SYA']);
Author::create(['name' => 'Mu\'jizah', 'singkatan' => 'MU\'']);
Author::create(['name' => 'Muh Husni Falah', 'singkatan' => 'FAL']);
Author::create(['name' => 'Muhajir', 'singkatan' => 'MUH']);
Author::create(['name' => 'Muhajir, Jaja Mujahid', 'singkatan' => 'MUH']);
Author::create(['name' => 'Muhamad Mas\'od', 'singkatan' => 'MAS']);
Author::create(['name' => 'Muhammad Akram Al-Adluny', 'singkatan' => 'ADL']);
Author::create(['name' => 'Muhammad Al-Mighwar, M.Ag.', 'singkatan' => 'MIG']);
Author::create(['name' => 'Muhammad Arifin, Dkk', 'singkatan' => 'ARI']);
Author::create(['name' => 'Muhammad Bin Sulaiman At-tamimi', 'singkatan' => 'BIN']);
Author::create(['name' => 'Muhammad Dahlan', 'singkatan' => 'DAH']);
Author::create(['name' => 'Muhammad Hemi Abdurrahman', 'singkatan' => 'MUH']);
Author::create(['name' => 'Muhammad musrofi', 'singkatan' => 'MUS']);
Author::create(['name' => 'Muhammad noor', 'singkatan' => 'NOO']);
Author::create(['name' => 'Muhammad Nur Anwar', 'singkatan' => 'ANW']);
Author::create(['name' => 'Muhammad Rifai', 'singkatan' => 'RIF']);
Author::create(['name' => 'Muhammad Syahwi', 'singkatan' => 'SYA']);
Author::create(['name' => 'Muhammad Syahwil', 'singkatan' => 'MUH']);
Author::create(['name' => 'Muhammad Taufiq', 'singkatan' => 'TAU']);
Author::create(['name' => 'Muhammad Tohirudin, S.T', 'singkatan' => 'TOH']);
Author::create(['name' => 'Muhammad, S.Pd, M. Hum', 'singkatan' => 'MUH']);
Author::create(['name' => 'Muklis', 'singkatan' => 'MUK']);
Author::create(['name' => 'Mulyadi', 'singkatan' => 'MUL']);
Author::create(['name' => 'Mulyadi, ST. MM', 'singkatan' => 'MUL']);
Author::create(['name' => 'Mulyono Sastronaryatmo', 'singkatan' => 'SAS']);
Author::create(['name' => 'munal Hani\'ah', 'singkatan' => 'HAN']);
Author::create(['name' => 'Munas P Ramli, Yanti hartanti, Iwan permana S.', 'singkatan' => 'RAM']);
Author::create(['name' => 'Muslikhah,S.Pd', 'singkatan' => 'MUS']);
Author::create(['name' => 'Mustahdi & Mustakim', 'singkatan' => 'MUS']);
Author::create(['name' => 'Mustofa H. Baabad', 'singkatan' => 'MUS']);
Author::create(['name' => 'Mustofa W, Hasyim', 'singkatan' => 'HAS']);
Author::create(['name' => 'Nanik Suryanto dan kawan', 'singkatan' => 'SUR']);
Author::create(['name' => 'Nasihin', 'singkatan' => 'NAS']);
Author::create(['name' => 'Nawal El Saadawi', 'singkatan' => 'SAA']);
Author::create(['name' => 'Neni Darmayanti', 'singkatan' => 'DAR']);
Author::create(['name' => 'Ni Nengah Sri Swathi', 'singkatan' => 'SWA']);
Author::create(['name' => 'Ni wayan Suwithi, DKK', 'singkatan' => 'SUW']);
Author::create(['name' => 'Niall mansfield', 'singkatan' => 'MAN']);
Author::create(['name' => 'Nikenasih Binatari, M.Si', 'singkatan' => 'BIN']);
Author::create(['name' => 'Nikmah Sunardjo', 'singkatan' => 'SUN']);
Author::create(['name' => 'Nikmah Sunardjo, Muhammad F, Dkk', 'singkatan' => 'SUN']);
Author::create(['name' => 'Nita Pujiastuti', 'singkatan' => 'PUJ']);
Author::create(['name' => 'Niugroho Noto Susanto', 'singkatan' => 'SUS']);
Author::create(['name' => 'Nizourohman', 'singkatan' => 'NIZ']);
Author::create(['name' => 'Noor Ms.Bakry', 'singkatan' => 'BAK']);
Author::create(['name' => 'Novia Nuryany', 'singkatan' => 'NUR']);
Author::create(['name' => 'Nunung Nurhayati', 'singkatan' => 'NUR']);
Author::create(['name' => 'Nunung Yuli Eti', 'singkatan' => 'WAR']);
Author::create(['name' => 'Nur Afidah', 'singkatan' => 'AFI']);
Author::create(['name' => 'Nur Annisa Rahmawati, ST.,MM', 'singkatan' => 'RAH']);
Author::create(['name' => 'Nur H.Rahmawati', 'singkatan' => 'RAH']);
Author::create(['name' => 'Nur Khalik', 'singkatan' => 'KHA']);
Author::create(['name' => 'Nur Khoiro Umatin', 'singkatan' => 'UMA']);
Author::create(['name' => 'Nur Rahadian Sari', 'singkatan' => 'RAH']);
Author::create(['name' => 'Nur Siwi Ismawati', 'singkatan' => 'ISM']);
Author::create(['name' => 'Nur siwi ismawati.S.S', 'singkatan' => 'ISM']);
Author::create(['name' => 'Nur Wahyu Rahmadi', 'singkatan' => 'RAH']);
Author::create(['name' => 'Nur wahyu Rohmadi', 'singkatan' => 'ROH']);
Author::create(['name' => 'Nuraksa Makodian & Lingga Wardhana', 'singkatan' => 'MAK']);
Author::create(['name' => 'Nursisto', 'singkatan' => 'NUR']);
Author::create(['name' => 'Nurul Akhmad', 'singkatan' => 'AKH']);
Author::create(['name' => 'Nurul Oktima', 'singkatan' => 'OKT']);
Author::create(['name' => 'Nurwulan Hidayati, S.Kom', 'singkatan' => 'HID']);
Author::create(['name' => 'Oka Aurora', 'singkatan' => 'AUR']);
Author::create(['name' => 'Oki Setiana Dewi', 'singkatan' => 'NAD']);
Author::create(['name' => 'Oki Setiana Dewi', 'singkatan' => 'SET']);
Author::create(['name' => 'Ongky Hojanto', 'singkatan' => 'HOJ']);
Author::create(['name' => 'Onno W. Purbo', 'singkatan' => 'PUR']);
Author::create(['name' => 'Orizuka', 'singkatan' => 'ORI']);
Author::create(['name' => 'Osa Pauliza', 'singkatan' => 'PAU']);
Author::create(['name' => 'Owen Bishop', 'singkatan' => 'BIS']);
Author::create(['name' => 'P.C. Kahono', 'singkatan' => 'KAH']);
Author::create(['name' => 'P.C.Kahono Dkk', 'singkatan' => 'KAH']);
Author::create(['name' => 'Palti R Tambah', 'singkatan' => 'TAM']);
Author::create(['name' => 'Pandan. Purwacandra', 'singkatan' => 'PUR']);
Author::create(['name' => 'Pardi Suratno', 'singkatan' => 'SUR']);
Author::create(['name' => 'Pardiyono', 'singkatan' => 'PAR']);
Author::create(['name' => 'Parmonangan Manurung', 'singkatan' => 'MAN']);
Author::create(['name' => 'Patrisius Istiarto Djiwandono', 'singkatan' => 'DJI']);
Author::create(['name' => 'Paul Indiyanto', 'singkatan' => 'IND']);
Author::create(['name' => 'paul steenson', 'singkatan' => 'STE']);
Author::create(['name' => 'Paul Strathern', 'singkatan' => 'STR']);
Author::create(['name' => 'Pdt.Janse Belinda', 'singkatan' => 'JAN']);
Author::create(['name' => 'Pemerintah', 'singkatan' => 'PEM']);
Author::create(['name' => 'Penelope Arlon', 'singkatan' => 'ARL']);
Author::create(['name' => 'penerbit andi,madcoms', 'singkatan' => 'AND']);
Author::create(['name' => 'penerbit andi,madcoms', 'singkatan' => 'MAD']);
Author::create(['name' => 'Peni Handayni', 'singkatan' => 'HAN']);
Author::create(['name' => 'Penny Smith', 'singkatan' => 'SMI']);
Author::create(['name' => 'Permata Press', 'singkatan' => 'ARA']);
Author::create(['name' => 'Permata Press', 'singkatan' => 'PRE']);
Author::create(['name' => 'Peter Evea, Stella Douglas, Peter Elliot, David Fairbairn, Ian Falconer', 'singkatan' => 'EVE']);
Author::create(['name' => 'Peter F. Drucker', 'singkatan' => 'DRU']);
Author::create(['name' => 'Peter watcyn-jones', 'singkatan' => 'JON']);
Author::create(['name' => 'Petra Setyani, S.Pd', 'singkatan' => 'SET']);
Author::create(['name' => 'Philip Berrill', 'singkatan' => 'BER']);
Author::create(['name' => 'piepet senja', 'singkatan' => 'SEN']);
Author::create(['name' => 'Piet Sondak', 'singkatan' => 'SON']);
Author::create(['name' => 'pijar88', 'singkatan' => 'PIJ']);
Author::create(['name' => 'Poconggg Syahreza', 'singkatan' => 'SYA']);
Author::create(['name' => 'poliyama', 'singkatan' => 'POL']);
Author::create(['name' => 'Pramana Padmodarmaya', 'singkatan' => 'PAD']);
Author::create(['name' => 'Prih Sumardjati', 'singkatan' => 'SUM']);
Author::create(['name' => 'Priyanto Hidayatullah', 'singkatan' => 'PRI']);
Author::create(['name' => 'Prof Dr Bambang Hidaya', 'singkatan' => 'HID']);
Author::create(['name' => 'prof Dr Sudarsono', 'singkatan' => 'SUD']);
Author::create(['name' => 'Prof,Dr. Ida Bagus Putrayasa,M.pd', 'singkatan' => 'PUT']);
Author::create(['name' => 'Prof,Dr.Nana Syaodih Sukmadinata', 'singkatan' => 'SUK']);
Author::create(['name' => 'Prof. Alwi Dahlan , Ph.D', 'singkatan' => 'DAH']);
Author::create(['name' => 'Prof. Dr. A. Muri Yusuf', 'singkatan' => 'MUR']);
Author::create(['name' => 'PROF. DR. Anna Poedjiadi', 'singkatan' => 'POE']);
Author::create(['name' => 'Prof. Dr. faisal Afiff , SPEC.LIC', 'singkatan' => 'AFI']);
Author::create(['name' => 'Prof. Dr. H. Kaelan, M.S', 'singkatan' => 'KAE']);
Author::create(['name' => 'Prof. Dr. h. Tukiran Taniredja, MM, dkk', 'singkatan' => 'TAN']);
Author::create(['name' => 'Prof. Dr. Harsuki, M.A.', 'singkatan' => 'HAR']);
Author::create(['name' => 'Prof. Dr. I Gde Pantja Astawa, SH, MH', 'singkatan' => 'GDE']);
Author::create(['name' => 'Prof. Dr. Mas\'ud Machoedz, M.B.A', 'singkatan' => 'MAC']);
Author::create(['name' => 'Prof. DR. Miftah Thoha, MPA', 'singkatan' => 'THO']);
Author::create(['name' => 'Prof. Dr. Mukhtar Dkk', 'singkatan' => 'MUK']);
Author::create(['name' => 'Prof. Dr. Mukhtar, M.Pd. DKK', 'singkatan' => 'MUK']);
Author::create(['name' => 'Prof. Dr. Ny. Canny samiawan dkk', 'singkatan' => 'SAM']);
Author::create(['name' => 'prof. Dr.bandhi delphi M.A.,A.E', 'singkatan' => 'DEL']);
Author::create(['name' => 'Prof. Dr.H. Buchari Alma', 'singkatan' => 'ALM']);
Author::create(['name' => 'Prof. DR.H. Kaelan, M, S, DRS.H. Achnad Zubaidi, Msi', 'singkatan' => 'KAE']);
Author::create(['name' => 'Prof. Dr.Ir. H. Ahmad Ramadhan Siregar', 'singkatan' => 'RAM']);
Author::create(['name' => 'Prof. Dr.sudarwan', 'singkatan' => 'SUD']);
Author::create(['name' => 'Prof. Dr.Sutardjo A. Wiramihardja, Psi', 'singkatan' => '']);
Author::create(['name' => 'Prof. Drs. H. Soegyarto Mangkuatmodjo', 'singkatan' => 'MAN']);
Author::create(['name' => 'Prof.Dr. H Buchari Alma', 'singkatan' => 'ALM']);
Author::create(['name' => 'Prof.Dr. Slamet Muljana', 'singkatan' => 'MUL']);
Author::create(['name' => 'prof.Dr. Wahyudi,M.Pd', 'singkatan' => 'WAH']);
Author::create(['name' => 'Prof.Dr.H.kaelan, M.S,Drs.H.Achmad Zubaidi,M.SI', 'singkatan' => 'KAE']);
Author::create(['name' => 'Prof.DR.Kaelan,M.S', 'singkatan' => 'KAE']);
Author::create(['name' => 'prof.ir. Sukandarrumidi, MSc.,PhD', 'singkatan' => 'SUK']);
Author::create(['name' => 'Prof.M.Dawam Raharjo', 'singkatan' => 'RAH']);
Author::create(['name' => 'Proft.Dr.sukanta Reksohadiprodjo. M. Com,DKK', 'singkatan' => 'REK']);
Author::create(['name' => 'Puji Ambarwati', 'singkatan' => 'AMB']);
Author::create(['name' => 'Punk Pribadi', 'singkatan' => 'PRI']);
Author::create(['name' => 'Purdi E.Chandra', 'singkatan' => 'CHA']);
Author::create(['name' => 'Purwo sutanto,Dkk', 'singkatan' => 'SUT']);
Author::create(['name' => 'Puspita RM', 'singkatan' => 'PUS']);
Author::create(['name' => 'Putri Minerua Mutiara', 'singkatan' => 'MUT']);
Author::create(['name' => 'R. Masri Sareb Putra', 'singkatan' => 'PUT']);
Author::create(['name' => 'R.Amien Nugroho', 'singkatan' => 'AMI']);
Author::create(['name' => 'R.H. Sianipar', 'singkatan' => 'SIA']);
Author::create(['name' => 'R.masri sareb pitra', 'singkatan' => 'PIT']);
Author::create(['name' => 'R.Masri Sareb Putra', 'singkatan' => 'PUT']);
Author::create(['name' => 'R.Roger', 'singkatan' => 'ROG']);
Author::create(['name' => 'Raditya Dika', 'singkatan' => 'DIK']);
Author::create(['name' => 'Rahmad Isnanto', 'singkatan' => 'ISN']);
Author::create(['name' => 'Rahmad Rafiudin', 'singkatan' => 'RAF']);
Author::create(['name' => 'Rahmad Widiyanto', 'singkatan' => 'WID']);
Author::create(['name' => 'Rahman Rohim hambar', 'singkatan' => 'HAM']);
Author::create(['name' => 'Rahmani dwi Fajarsih', 'singkatan' => 'FAJ']);
Author::create(['name' => 'Rahmat M', 'singkatan' => 'RAH']);
Author::create(['name' => 'Rahmat Putra', 'singkatan' => 'PUT']);
Author::create(['name' => 'Rahmat Rafiudin', 'singkatan' => 'RAF']);
Author::create(['name' => 'Rahmat Rafiudin', 'singkatan' => 'RAH']);
Author::create(['name' => 'Ramadhan K H', 'singkatan' => 'RAM']);
Author::create(['name' => 'Ramadhan S. Pernyata', 'singkatan' => 'RAM']);
Author::create(['name' => 'Rangsang Purnama', 'singkatan' => 'PUR']);
Author::create(['name' => 'Rantinah', 'singkatan' => 'RAN']);
Author::create(['name' => 'Ratna Hapsari & M. Adil', 'singkatan' => 'HAP']);
Author::create(['name' => 'Ratna Rima Melati', 'singkatan' => 'MEL']);
Author::create(['name' => 'Ratna Rima Melati,Eko Sujatmiko', 'singkatan' => 'MEL']);
Author::create(['name' => 'Ray Smilor', 'singkatan' => 'SMI']);
Author::create(['name' => 'Rayani sriwidodo', 'singkatan' => 'SRI']);
Author::create(['name' => 'Rechel wardley dan jane bingham', 'singkatan' => 'WAR']);
Author::create(['name' => 'Redaksi Komputeraktif', 'singkatan' => 'KOM']);
Author::create(['name' => 'Redaksi Sinar Grafika', 'singkatan' => 'SIN']);
Author::create(['name' => 'Redi Panuju', 'singkatan' => 'PAN']);
Author::create(['name' => 'Rendra', 'singkatan' => 'REN']);
Author::create(['name' => 'Rendra Towidjojo', 'singkatan' => 'TOW']);
Author::create(['name' => 'Reni Agustin P, S.Pd, Eni hestuti, S.S', 'singkatan' => 'AGU']);
Author::create(['name' => 'Restoran Ekawatiningsih,dkk', 'singkatan' => 'EKA']);
Author::create(['name' => 'Retno Listyarti', 'singkatan' => 'LIS']);
Author::create(['name' => 'Retno Listyarti,Setiadi', 'singkatan' => 'LIS']);
Author::create(['name' => 'Retno Widayanti', 'singkatan' => 'WID']);
Author::create(['name' => 'richard D.Lewis', 'singkatan' => 'LEW']);
Author::create(['name' => 'Richard S.Sloma', 'singkatan' => 'SLO']);
Author::create(['name' => 'Rick Engel', 'singkatan' => 'ENG']);
Author::create(['name' => 'Ridi Ferdiana', 'singkatan' => 'FER']);
Author::create(['name' => 'Rini Apriani, Spd', 'singkatan' => 'APR']);
Author::create(['name' => 'Ritan Saragih, SE., MBA', 'singkatan' => 'SAR']);
Author::create(['name' => 'Riyanti', 'singkatan' => 'RIY']);
Author::create(['name' => 'Riza Astuti Y.W', 'singkatan' => 'AST']);
Author::create(['name' => 'Robert koger', 'singkatan' => 'KOG']);
Author::create(['name' => 'Roger E. Hernandez', 'singkatan' => 'HER']);
Author::create(['name' => 'Roger R. Pressman, Ph.D', 'singkatan' => 'PRE']);
Author::create(['name' => 'Rohy', 'singkatan' => 'ROH']);
Author::create(['name' => 'Romana Dian P.', 'singkatan' => 'DIA']);
Author::create(['name' => 'Ronald Budi', 'singkatan' => 'BUD']);
Author::create(['name' => 'Rostamailis, dkk', 'singkatan' => 'ROS']);
Author::create(['name' => 'Rozali Abdullah,S.H.', 'singkatan' => 'ABD']);
Author::create(['name' => 'Rudi Hidayat', 'singkatan' => 'HID']);
Author::create(['name' => 'Rukmadi Warsito', 'singkatan' => 'WAR']);
Author::create(['name' => 'Rully Bramasti', 'singkatan' => 'BRA']);
Author::create(['name' => 'Rully Nasrullah', 'singkatan' => 'NAS']);
Author::create(['name' => 'Rusdianto', 'singkatan' => 'RUS']);
Author::create(['name' => 'Russell Barland', 'singkatan' => 'BAR']);
Author::create(['name' => 'Ryan Sugiarto', 'singkatan' => 'SUG']);
Author::create(['name' => 'S\'to', 'singkatan' => 'S\'TO']);
Author::create(['name' => 'S. Wulandari', 'singkatan' => 'WUL']);
Author::create(['name' => 'S.C. Bloch', 'singkatan' => 'BLO']);
Author::create(['name' => 'S.Sartono,S.Pd, Sujito, BA, Drs. Bambang Sugeng M.', 'singkatan' => 'SUJ']);
Author::create(['name' => 'Sabbana Azmi', 'singkatan' => 'AZM']);
Author::create(['name' => 'Sadali', 'singkatan' => 'SAD']);
Author::create(['name' => 'Saefur Rochmat', 'singkatan' => 'ROC']);
Author::create(['name' => 'saiful hadi El-Sutha', 'singkatan' => 'SUT']);
Author::create(['name' => 'Saini.K.M', 'singkatan' => 'SAI']);
Author::create(['name' => 'Saksono Prijanto', 'singkatan' => 'PRI']);
Author::create(['name' => 'Salamah Agung, Nengseh Juaningsih', 'singkatan' => 'AGU']);
Author::create(['name' => 'Samijo - Samidi', 'singkatan' => 'SAM']);
Author::create(['name' => 'Samsul Farid', 'singkatan' => 'FAR']);
Author::create(['name' => 'Sara Tee', 'singkatan' => 'TEE']);
Author::create(['name' => 'Sarah Noordeviana', 'singkatan' => 'NOR']);
Author::create(['name' => 'Sarbani B.A', 'singkatan' => 'SAR']);
Author::create(['name' => 'Sarbani. B. A', 'singkatan' => 'SAR']);
Author::create(['name' => 'sari B.Kusumayudha', 'singkatan' => 'KUS']);
Author::create(['name' => 'Sari Pusparini Soleh', 'singkatan' => 'SOL']);
Author::create(['name' => 'Sartono wirodikrama', 'singkatan' => 'WIR']);
Author::create(['name' => 'Sean Hasyim', 'singkatan' => 'HAS']);
Author::create(['name' => 'sekolah menengah kejuruan', 'singkatan' => 'SMK']);
Author::create(['name' => 'Sekretariat Jenderal MPR RI', 'singkatan' => 'JEN']);
Author::create(['name' => 'Sekretaris Jendral MPR RI', 'singkatan' => 'JEN']);
Author::create(['name' => 'Sekretaris Jendral MPR RI', 'singkatan' => 'MPR']);
Author::create(['name' => 'Semuil Tjiharjadi,DT,MM,MT,Dkk', 'singkatan' => 'TJI']);
Author::create(['name' => 'Seno Adjie', 'singkatan' => 'ADJ']);
Author::create(['name' => 'Seri ketrampilan', 'singkatan' => 'KET']);
Author::create(['name' => 'Setiadi, Retno Listyarti', 'singkatan' => 'LIS']);
Author::create(['name' => 'Setiadi, Retno Listyarti', 'singkatan' => 'SET']);
Author::create(['name' => 'Sheddy Nagara Tjandra,Dkk', 'singkatan' => 'TJA']);
Author::create(['name' => 'Shyla K Lande - Eka Mulya Astuti', 'singkatan' => 'LAN']);
Author::create(['name' => 'SIC', 'singkatan' => '']);
Author::create(['name' => 'Sidik kertapati', 'singkatan' => 'KER']);
Author::create(['name' => 'Sidiq Syamsul Hidayat', 'singkatan' => 'SIQ']);
Author::create(['name' => 'sigid Widagdo', 'singkatan' => 'WID']);
Author::create(['name' => 'Simon Garner', 'singkatan' => 'GAR']);
Author::create(['name' => 'Singgih Sastradihardja', 'singkatan' => 'SAS']);
Author::create(['name' => 'Siswoyo', 'singkatan' => 'SIS']);
Author::create(['name' => 'Siti Nurhasanah, S.E', 'singkatan' => 'NUR']);
Author::create(['name' => 'Siti Nurhasanah, S.E', 'singkatan' => 'WET']);
Author::create(['name' => 'Siti Warida Q, Sunarto sunardi, Rubiyatno', 'singkatan' => 'WAR']);
Author::create(['name' => 'Siti Zuhan Y', 'singkatan' => 'ZUH']);
Author::create(['name' => 'Sitiatava Rizema Putra', 'singkatan' => 'RIZ']);
Author::create(['name' => 'Sitok Srengenge', 'singkatan' => 'SRE']);
Author::create(['name' => 'Sjahmien Moehji', 'singkatan' => 'MOE']);
Author::create(['name' => 'Slamet Riyanto', 'singkatan' => 'SLA']);
Author::create(['name' => 'Soedjono', 'singkatan' => 'SOE']);
Author::create(['name' => 'Soeroso', 'singkatan' => 'SOE']);
Author::create(['name' => 'Sri Hartini mahmudi, Kiki ariyanti sugeng DKK', 'singkatan' => 'MAH']);
Author::create(['name' => 'Sri Hermawati Dwi arini,Dkk', 'singkatan' => 'ARI']);
Author::create(['name' => 'Sri Lestari, ST', 'singkatan' => 'LES']);
Author::create(['name' => 'Sri lestari,S.Pd', 'singkatan' => 'LES']);
Author::create(['name' => 'Sri Mintarjo, S.Si.', 'singkatan' => 'MIN']);
Author::create(['name' => 'Sri mintarto', 'singkatan' => 'MIN']);
Author::create(['name' => 'Sri Nuraini', 'singkatan' => 'NUR']);
Author::create(['name' => 'Sri Puspita Murni', 'singkatan' => 'MUR']);
Author::create(['name' => 'Sri rinidwiari, dkk', 'singkatan' => 'DWI']);
Author::create(['name' => 'Sri Sayekti', 'singkatan' => 'SRI']);
Author::create(['name' => 'Sri Soyak H. M, Jaruki', 'singkatan' => 'JAR']);
Author::create(['name' => 'Sri Wahyuni', 'singkatan' => 'WAH']);
Author::create(['name' => 'Sri Waluyanti', 'singkatan' => 'WAL']);
Author::create(['name' => 'Sri Waluyati Sandi', 'singkatan' => 'SAN']);
Author::create(['name' => 'Sri Winarsih', 'singkatan' => 'WIN']);
Author::create(['name' => 'ST Takdir Alis Jahbona', 'singkatan' => 'JAH']);
Author::create(['name' => 'Stave Parker', 'singkatan' => 'PAR']);
Author::create(['name' => 'Subandi , S.Pd', 'singkatan' => 'SUB']);
Author::create(['name' => 'Sucipto', 'singkatan' => 'SUC']);
Author::create(['name' => 'Sudaryanto', 'singkatan' => 'SUD']);
Author::create(['name' => 'Sudino Espe', 'singkatan' => 'ESP']);
Author::create(['name' => 'Sudirman', 'singkatan' => 'SUD']);
Author::create(['name' => 'sue thomas,ian forster', 'singkatan' => 'THO']);
Author::create(['name' => 'sugeng aryanto', 'singkatan' => 'ARY']);
Author::create(['name' => 'Sugeng Suprayogi, Spd, Drs Idris mandang', 'singkatan' => 'SUP']);
Author::create(['name' => 'Sugiantoro, Ronny', 'singkatan' => 'SUG']);
Author::create(['name' => 'Sugito', 'singkatan' => 'SUG']);
Author::create(['name' => 'Sugiyanto, dkk', 'singkatan' => 'SUG']);
Author::create(['name' => 'Sugiyarto', 'singkatan' => 'SUG']);
Author::create(['name' => 'Suharyanto, S.H', 'singkatan' => 'SUH']);
Author::create(['name' => 'Suka mitra kompetensi', 'singkatan' => 'SMK']);
Author::create(['name' => 'Sukadi', 'singkatan' => 'SUK']);
Author::create(['name' => 'Sukardi Wisnubroto', 'singkatan' => 'WIS']);
Author::create(['name' => 'Sukini,Dkk', 'singkatan' => 'ART']);
Author::create(['name' => 'Sukino', 'singkatan' => 'SUK']);
Author::create(['name' => 'Sukino Suparmin', 'singkatan' => 'SUP']);
Author::create(['name' => 'Sularto, dkk.', 'singkatan' => 'SUL']);
Author::create(['name' => 'Sumadi, Dkk', 'singkatan' => 'SUM']);
Author::create(['name' => 'Sumadi, S.Pd,.M.Si, Dkk', 'singkatan' => 'SUM']);
Author::create(['name' => 'Sumahadi marsis, TD asmadi, D kk', 'singkatan' => 'MAR']);
Author::create(['name' => 'Suman H. S', 'singkatan' => 'SUM']);
Author::create(['name' => 'Sumaryono Suryokusumo', 'singkatan' => 'SUR']);
Author::create(['name' => 'Suminto A, Suyati', 'singkatan' => 'SUM']);
Author::create(['name' => 'Sumurung Basa Silaban', 'singkatan' => 'SUM']);
Author::create(['name' => 'Suparno', 'singkatan' => 'SUP']);
Author::create(['name' => 'Suparno sastra M', 'singkatan' => 'SAS']);
Author::create(['name' => 'Suparwoto', 'singkatan' => 'SUP']);
Author::create(['name' => 'Suprapto, Sri Ruspito Murni', 'singkatan' => 'SUP']);
Author::create(['name' => 'Supriyatingtyas', 'singkatan' => 'SUP']);
Author::create(['name' => 'Suryati,Dkk', 'singkatan' => 'SUR']);
Author::create(['name' => 'Suwarna Pringgawidagdo', 'singkatan' => 'PRI']);
Author::create(['name' => 'Suwelo Hadiwijoyo', 'singkatan' => 'HAD']);
Author::create(['name' => 'Suyono Suyanto', 'singkatan' => 'SUY']);
Author::create(['name' => 'syafril Teha Noer', 'singkatan' => 'NOE']);
Author::create(['name' => 'Syafril Teha Noer,Dkk', 'singkatan' => 'NOE']);
Author::create(['name' => 'Syaikh Dr.Abdullah Nasih Ulwan', 'singkatan' => 'ULW']);
Author::create(['name' => 'Syamsudin & Hermanto', 'singkatan' => 'SYA']);
Author::create(['name' => 'Syamsul Rijal Hamid', 'singkatan' => 'RIJ']);
Author::create(['name' => 'Syarief Hidayatullah', 'singkatan' => 'HID']);
Author::create(['name' => 'Syeikh Fauzi Sa\'id', 'singkatan' => 'SAI']);
Author::create(['name' => 'Syukri Ghozati', 'singkatan' => 'GHO']);
Author::create(['name' => 'Tammi Prastowo', 'singkatan' => 'PRA']);
Author::create(['name' => 'Tammi Prastowo, S.Sos.', 'singkatan' => 'PRA']);
Author::create(['name' => 'Taufik Daraming Tahir & Helfi Kardit', 'singkatan' => 'TAH']);
Author::create(['name' => 'Taufiq Hidayat', 'singkatan' => 'HID']);
Author::create(['name' => 'Team Harmoni', 'singkatan' => 'HAR']);
Author::create(['name' => 'Tedi Setyadi Permana', 'singkatan' => 'PER']);
Author::create(['name' => 'Teguh Wahyono, S.Kom', 'singkatan' => 'WAH']);
Author::create(['name' => 'Tere Liye', 'singkatan' => 'LIY']);
Author::create(['name' => 'Terri lees', 'singkatan' => 'LEE']);
Author::create(['name' => 'Teswanti Suci M', 'singkatan' => 'SUC']);
Author::create(['name' => 'Th. M. Sudarwati & Eudia Grace', 'singkatan' => 'SUD']);
Author::create(['name' => 'The Java Motivator Community', 'singkatan' => 'THE']);
Author::create(['name' => 'Theresa Greenaway', 'singkatan' => 'GRE']);
Author::create(['name' => 'Thoyibah Handayani', 'singkatan' => 'HAN']);
Author::create(['name' => 'Tia mutiara, Dkk', 'singkatan' => 'MUT']);
Author::create(['name' => 'Tim Akademik IPIEMS', 'singkatan' => 'TIM']);
Author::create(['name' => 'Tim Belia', 'singkatan' => 'BEL']);
Author::create(['name' => 'Tim Eksakta', 'singkatan' => 'EKS']);
Author::create(['name' => 'Tim Kajian Amandemen', 'singkatan' => 'TIM']);
Author::create(['name' => 'Tim Metode Ilham', 'singkatan' => 'TIM']);
Author::create(['name' => 'Tim Pustaka Lebah', 'singkatan' => 'TIM']);
Author::create(['name' => 'Tim pustaka spirit', 'singkatan' => 'SPI']);
Author::create(['name' => 'Tim Redaksi Fokus Media', 'singkatan' => 'TIM']);
Author::create(['name' => 'Tim Supermath', 'singkatan' => 'SUP']);
Author::create(['name' => 'Tim Teropong UN', 'singkatan' => 'TIM']);
Author::create(['name' => 'Timothy yani, julianto, & Adnan H.P', 'singkatan' => 'YAN']);
Author::create(['name' => 'Tine Maria kuswati,Dkk', 'singkatan' => 'KUS']);
Author::create(['name' => 'Tom fleck, Ron Quinn', 'singkatan' => 'FLE']);
Author::create(['name' => 'Tom jacson', 'singkatan' => 'JAC']);
Author::create(['name' => 'Tom Thomas', 'singkatan' => 'THO']);
Author::create(['name' => 'Tomislav Sebcanski', 'singkatan' => 'SEB']);
Author::create(['name' => 'Toni purwono, SE.,M.M', 'singkatan' => 'PUR']);
Author::create(['name' => 'Tracey Kelly', 'singkatan' => 'KEL']);
Author::create(['name' => 'Tri Haryanto,S.Si', 'singkatan' => 'HAR']);
Author::create(['name' => 'Tri Kuntoro Priyambodo. Dodi Heriadi', 'singkatan' => 'PRI']);
Author::create(['name' => 'Tridoyo,S.Sos', 'singkatan' => 'TRI']);
Author::create(['name' => 'Triyani', 'singkatan' => 'TRI']);
Author::create(['name' => 'Tutang', 'singkatan' => 'TUT']);
Author::create(['name' => 'U.E. Wardhani,dkk', 'singkatan' => 'WAR']);
Author::create(['name' => 'Ubed Abdilah Syarif,Dkk', 'singkatan' => 'SYA']);
Author::create(['name' => 'Ucak', 'singkatan' => 'UCA']);
Author::create(['name' => 'Ule sulistyo, S.IP. Dyah Sumastuti', 'singkatan' => 'SUL']);
Author::create(['name' => 'Umar Kayam', 'singkatan' => 'KAY']);
Author::create(['name' => 'Umi muawanah, dkk', 'singkatan' => 'MUA']);
Author::create(['name' => 'Upik kusuma wardani, S.Pd, Cahyono,Spd', 'singkatan' => 'WAR']);
Author::create(['name' => 'Upita Agustine', 'singkatan' => 'AGU']);
Author::create(['name' => 'Usman', 'singkatan' => 'USM']);
Author::create(['name' => 'Ust. Ahmad Zacky El-Syafa', 'singkatan' => 'ZAC']);
Author::create(['name' => 'Ust. Labib Mz.', 'singkatan' => 'LAB']);
Author::create(['name' => 'Ust. Yusuf Mansyur', 'singkatan' => 'MAN']);
Author::create(['name' => 'Ustadz Ali Amrin Al Qurawy', 'singkatan' => 'ALI']);
Author::create(['name' => 'Uti Darmawati', 'singkatan' => 'DAR']);
Author::create(['name' => 'Uti darmawati', 'singkatan' => 'TRI']);
Author::create(['name' => 'uti Darmawati,S.S', 'singkatan' => 'DAR']);
Author::create(['name' => 'Uus Rusmawan', 'singkatan' => 'RUS']);
Author::create(['name' => 'Uyless Black', 'singkatan' => 'BLA']);
Author::create(['name' => 'Varina Diah Wijayanti', 'singkatan' => 'WIJ']);
Author::create(['name' => 'Veronica Latifiane', 'singkatan' => 'LAT']);
Author::create(['name' => 'Vic Amber', 'singkatan' => 'AMB']);
Author::create(['name' => 'Vina Dwi L', 'singkatan' => 'DWI']);
Author::create(['name' => 'Vina Dwi Laning', 'singkatan' => 'LAN']);
Author::create(['name' => 'Vyctoria', 'singkatan' => 'VYC']);
Author::create(['name' => 'W. Dasanti', 'singkatan' => 'DAS']);
Author::create(['name' => 'W.J.S Poerwadarminta', 'singkatan' => 'POE']);
Author::create(['name' => 'Wacana Adhitya', 'singkatan' => 'SOE']);
Author::create(['name' => 'Wahab', 'singkatan' => 'WAH']);
Author::create(['name' => 'Wahana Komputer', 'singkatan' => 'KOM']);
Author::create(['name' => 'Wahana Komputer', 'singkatan' => 'WAH']);
Author::create(['name' => 'Wahjudi Djaja', 'singkatan' => 'DJA']);
Author::create(['name' => 'Wahjudi Djaja, S.S.', 'singkatan' => 'DJA']);
Author::create(['name' => 'Wahyu wibowo', 'singkatan' => 'WIB']);
Author::create(['name' => 'Wahyudi Djaja', 'singkatan' => 'DJA']);
Author::create(['name' => 'waldjinah', 'singkatan' => 'WAL']);
Author::create(['name' => 'Walidi, S.Pd', 'singkatan' => 'WAL']);
Author::create(['name' => 'Wasito S', 'singkatan' => 'WAS']);
Author::create(['name' => 'Wawan Tunggul Alam', 'singkatan' => 'ALA']);
Author::create(['name' => 'Wendi Widya R.D', 'singkatan' => 'WID']);
Author::create(['name' => 'Wendi widya ratna dewi', 'singkatan' => 'DEW']);
Author::create(['name' => 'Wendy Horobin & Caroline Bingham', 'singkatan' => 'HOR']);
Author::create(['name' => 'westriningsih', 'singkatan' => 'WES']);
Author::create(['name' => 'Widarto', 'singkatan' => 'WID']);
Author::create(['name' => 'wiharsono kurniawan', 'singkatan' => 'KUR']);
Author::create(['name' => 'Wila Andrian soekarjo Loeri', 'singkatan' => 'LOE']);
Author::create(['name' => 'William Hunter', 'singkatan' => 'HUN']);
Author::create(['name' => 'Winarno', 'singkatan' => 'WIN']);
Author::create(['name' => 'Winarno & Supardi', 'singkatan' => 'WIN']);
Author::create(['name' => 'Winarti', 'singkatan' => 'WIN']);
Author::create(['name' => 'windoyo,S.E.,M.M', 'singkatan' => 'WIN']);
Author::create(['name' => 'Windra Swastika', 'singkatan' => 'WIN']);
Author::create(['name' => 'Winendra Adi,Dkk', 'singkatan' => 'ADI']);
Author::create(['name' => 'wirawan sumbondo, dkk', 'singkatan' => 'SUM']);
Author::create(['name' => 'wono setyo budhi', 'singkatan' => 'BUD']);
Author::create(['name' => 'woro Vidya Ayuningtias', 'singkatan' => 'AYU']);
Author::create(['name' => 'wowok', 'singkatan' => 'WOK']);
Author::create(['name' => 'Wulandari', 'singkatan' => 'WUL']);
Author::create(['name' => 'Xu Zi Niaga', 'singkatan' => 'NIA']);
Author::create(['name' => 'Y. Budi Artati, S.S.', 'singkatan' => 'ART']);
Author::create(['name' => 'Y.Budi Artati', 'singkatan' => 'ART']);
Author::create(['name' => 'Y.Budi Artati. S.S', 'singkatan' => 'ART']);
Author::create(['name' => 'Y.P.ari Nugroho', 'singkatan' => 'NUG']);
Author::create(['name' => 'Yadi Mulyadi', 'singkatan' => 'MUL']);
Author::create(['name' => 'Yana Suryana', 'singkatan' => 'SUR']);
Author::create(['name' => 'Yanner Irwan Mahendra', 'singkatan' => 'IRW']);
Author::create(['name' => 'yanti Isa & Triani Retno', 'singkatan' => 'ISA']);
Author::create(['name' => 'Yasir Arafat', 'singkatan' => 'ARA']);
Author::create(['name' => 'YB. Margantoro', 'singkatan' => 'MAR']);
Author::create(['name' => 'Yeni Husanaeni', 'singkatan' => 'HUS']);
Author::create(['name' => 'Yeni Mulyani, Supriyatin', 'singkatan' => 'MUL']);
Author::create(['name' => 'Yin Lin Jun', 'singkatan' => 'JUN']);
Author::create(['name' => 'Yohan Jati Waloeyan', 'singkatan' => 'JAT']);
Author::create(['name' => 'Yohana', 'singkatan' => 'TOH']);
Author::create(['name' => 'Yohana', 'singkatan' => 'YOH']);
Author::create(['name' => 'Yohana Niken R', 'singkatan' => 'NIK']);
Author::create(['name' => 'Yola Ifana Putra, S.Ti', 'singkatan' => 'IFA']);
Author::create(['name' => 'Yopie Nugraha', 'singkatan' => 'NUG']);
Author::create(['name' => 'Young Hoon Ko', 'singkatan' => 'HOO']);
Author::create(['name' => 'Yuan Acitra', 'singkatan' => 'ACI']);
Author::create(['name' => 'yudha Pandu', 'singkatan' => 'PAN']);
Author::create(['name' => 'Yudi Suparyanto', 'singkatan' => 'SUP']);
Author::create(['name' => 'Yudi Supayanto', 'singkatan' => 'SUP']);
Author::create(['name' => 'Yudianti herawati & TIM', 'singkatan' => 'HER']);
Author::create(['name' => 'Yudianti Herawati, M.A.', 'singkatan' => 'HER']);
Author::create(['name' => 'Yuli Rohmatun', 'singkatan' => 'ROH']);
Author::create(['name' => 'Yuliasi Soekarno,Dkk', 'singkatan' => 'SOE']);
Author::create(['name' => 'Yuniarti D.arini', 'singkatan' => 'ARI']);
Author::create(['name' => 'Yunus Kuntawi Aji', 'singkatan' => 'KUN']);
Author::create(['name' => 'Yusir arafat', 'singkatan' => 'ARA']);
Author::create(['name' => 'Yusniasari Shinta dewi', 'singkatan' => 'DEW']);
Author::create(['name' => 'Yustina,ahmad Iskak', 'singkatan' => 'YUS']);
Author::create(['name' => 'Yustinah', 'singkatan' => 'YUS']);
Author::create(['name' => 'Yustinus Prastowo', 'singkatan' => 'PRA']);
Author::create(['name' => 'yuyun yuningsih, Spd, susilo Wardani, S.Pd', 'singkatan' => 'YUN']);
Author::create(['name' => 'Yuyunardi', 'singkatan' => 'YUY']);
Author::create(['name' => 'Yuyus Kardiman , dkk', 'singkatan' => 'KAR']);
Author::create(['name' => 'Zaenal Arifin', 'singkatan' => 'ARF']);
Author::create(['name' => 'Zaenal Arifin', 'singkatan' => 'ARI']);
Author::create(['name' => 'Zaenuddin HM', 'singkatan' => 'ZAE']);
Author::create(['name' => 'Zikrul', 'singkatan' => 'ZIK']);
Author::create(['name' => 'Zuber Usman', 'singkatan' => 'USM']);
Author::create(['name' => 'Zunaidah Subro', 'singkatan' => 'SUB']);

    }
}
