<?php

use Illuminate\Database\Seeder;
use App\Book;
use App\Author;
use App\Member;
use App\User;
use App\Publisher;
use App\Category;
use App\BorrowLog;
use Carbon\Carbon;

class BooksSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {        

Book::create(['no_induk' => '4062','title' => 'kesadaran nasional dari kolonalisme sampai kemerdekaan jilid 1','author_id' => '881', 'publisher_id' => '226', 'published_location' => 'Yogyakarta', 'published_year' => '2008', 'book_year' => '2008','classification_code' => '910001', 'initial' => 'K','amount' => '1','category_id' => '93', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '4063','title' => 'kesadaran nasional dari kolonalisme sampai kemerdekaan jilid 2','author_id' => '881', 'publisher_id' => '226', 'published_location' => 'Yogyakarta', 'published_year' => '2008', 'book_year' => '2008','classification_code' => '910002', 'initial' => 'K','amount' => '1','category_id' => '93', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '4064','title' => 'Mandiri sejarah jilid 2 untuk SMA dan MAK kelas XI program ilmu sosial','author_id' => '662', 'publisher_id' => '122', 'published_location' => 'Jakarta', 'published_year' => '2009', 'book_year' => '2009','classification_code' => '910003', 'initial' => 'M','amount' => '1','category_id' => '93', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '4065','title' => 'mengerti sejarah','author_id' => '667', 'publisher_id' => '399', 'published_location' => 'Jakarta', 'published_year' => '1969', 'book_year' => '1969','classification_code' => '910004', 'initial' => 'M','amount' => '3','category_id' => '93', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '4068','title' => 'Sejarah Gerakan Buruh Indonesia','author_id' => '958', 'publisher_id' => '340', 'published_location' => '', 'published_year' => '2002', 'book_year' => '2002','classification_code' => '910005', 'initial' => 'S','amount' => '1','category_id' => '93', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '4069','title' => 'Sejarah jilid I untuk SMA X program ilmu sosial','author_id' => '530', 'publisher_id' => '122', 'published_location' => 'Jakarta', 'published_year' => '2006', 'book_year' => '2006','classification_code' => '910006', 'initial' => 'S','amount' => '2','category_id' => '93', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '4071','title' => 'Sejarah jilid II untuk SMA XI Program ilmu sosial','author_id' => '530', 'publisher_id' => '122', 'published_location' => 'Jakarta', 'published_year' => '2006', 'book_year' => '2006','classification_code' => '910007', 'initial' => 'S','amount' => '2','category_id' => '93', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '4073','title' => 'Sejarah jilid III untuk SMA kelas XII','author_id' => '530', 'publisher_id' => '122', 'published_location' => 'Jakarta', 'published_year' => '2006', 'book_year' => '2006','classification_code' => '910008', 'initial' => 'S','amount' => '5','category_id' => '93', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '4078','title' => 'Sejarah kelas 1 SMK','author_id' => '1032', 'publisher_id' => '368', 'published_location' => 'Klaten', 'published_year' => '2003', 'book_year' => '2003','classification_code' => '910009', 'initial' => 'S','amount' => '1','category_id' => '93', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '4079','title' => 'Sejarah Nasional','author_id' => '994', 'publisher_id' => '60', 'published_location' => 'Jakarta', 'published_year' => '2004', 'book_year' => '2004','classification_code' => '910010', 'initial' => 'S','amount' => '1','category_id' => '93', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '4080','title' => 'sejarah nasional dan sejarah umum kelas 2','author_id' => '968', 'publisher_id' => '270', 'published_location' => 'Surakarta', 'published_year' => '2002', 'book_year' => '2002','classification_code' => '910011', 'initial' => 'S','amount' => '1','category_id' => '93', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '4081','title' => 'Sejarah Nasional dan sejarah umum kelas 3','author_id' => '969', 'publisher_id' => '270', 'published_location' => 'Surakarta', 'published_year' => '2002', 'book_year' => '2002','classification_code' => '910,012,01', 'initial' => 'S','amount' => '80','category_id' => '93', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '4161','title' => 'Sejarah Pergerakan Nasional','author_id' => '857', 'publisher_id' => '339', 'published_location' => 'Yogyakarta', 'published_year' => '2001', 'book_year' => '2001','classification_code' => '910013', 'initial' => 'S','amount' => '1','category_id' => '93', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '4162','title' => 'sejarah ringkas pahlawan nasional buku 1','author_id' => '1147', 'publisher_id' => '122', 'published_location' => 'Jakarta', 'published_year' => '2006', 'book_year' => '2006','classification_code' => '910014', 'initial' => 'S','amount' => '5','category_id' => '93', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '4167','title' => 'sejarah ringkas pahlawan nasional buku 2','author_id' => '1147', 'publisher_id' => '122', 'published_location' => 'Jakarta', 'published_year' => '2006', 'book_year' => '2006','classification_code' => '910015', 'initial' => 'S','amount' => '5','category_id' => '93', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '4172','title' => 'Sejarah untuk SMA dan MA kelas XII program Bahasa','author_id' => '706', 'publisher_id' => '122', 'published_location' => 'Jakarta', 'published_year' => '2007', 'book_year' => '2007','classification_code' => '910016', 'initial' => 'S','amount' => '1','category_id' => '93', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '4173','title' => 'Sejarah untuk SMA dan MA program IPA kelas XI','author_id' => '706', 'publisher_id' => '122', 'published_location' => 'Jakarta', 'published_year' => '2007', 'book_year' => '2007','classification_code' => '910017', 'initial' => 'S','amount' => '1','category_id' => '93', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '4174','title' => 'Sejarah untuk SMA dan MA Kelas XI program Bahasa','author_id' => '706', 'publisher_id' => '122', 'published_location' => 'Jakarta', 'published_year' => '2007', 'book_year' => '2007','classification_code' => '910018', 'initial' => 'S','amount' => '1','category_id' => '93', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '5654','title' => 'Sejarah Umum dan Nasional untuk SMU Kelas 3','author_id' => '956', 'publisher_id' => '270', 'published_location' => 'Surakarta', 'published_year' => '1996', 'book_year' => '1996','classification_code' => '910.019.001', 'initial' => 'S','amount' => '1','category_id' => '93', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '18133','title' => 'Sejarah Indonesia untuk SMA/MA Kelas X Kelompok Wajib ( K-13 )','author_id' => '914', 'publisher_id' => '284', 'published_location' => 'Jakarta', 'published_year' => '2014', 'book_year' => '2014','classification_code' => '910.020.001', 'initial' => 'S','amount' => '8','category_id' => '93', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '18141','title' => 'Sejarah Indonesia untuk SMA/MAK Kelas X ( K-13 )','author_id' => '914', 'publisher_id' => '284', 'published_location' => 'Jakarta', 'published_year' => '2014', 'book_year' => '2014','classification_code' => '910.021.001', 'initial' => 'S','amount' => '10','category_id' => '93', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '18151','title' => 'Sejarah Indonesia untuk SMK/MAK Kelas XI ( K-13 )','author_id' => '914', 'publisher_id' => '284', 'published_location' => 'Jakarta', 'published_year' => '2014', 'book_year' => '2014','classification_code' => '910.022.001', 'initial' => 'S','amount' => '1','category_id' => '93', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '18152','title' => 'Sejarah Indonesia untuk SMA-MA/SMK Kelas X wajib ( K-13 )','author_id' => '965', 'publisher_id' => '416', 'published_location' => 'Bandung', 'published_year' => '2013', 'book_year' => '2013','classification_code' => '910.023.001', 'initial' => 'S','amount' => '2','category_id' => '93', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '4175','title' => 'Buku pintar Pahlawan Nasional termasuk pahlawan bangsa terbaru','author_id' => '720', 'publisher_id' => '372', 'published_location' => 'Batam', 'published_year' => '2007', 'book_year' => '2007','classification_code' => '920001', 'initial' => 'B','amount' => '1','category_id' => '92', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '4176','title' => 'mengenai pahlawan nasional','author_id' => '852', 'publisher_id' => '305', 'published_location' => 'Jakarta', 'published_year' => '2005', 'book_year' => '2005','classification_code' => '920002', 'initial' => 'M','amount' => '1','category_id' => '92', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '4177','title' => 'mengenal pemerintah indonesia','author_id' => '77', 'publisher_id' => '67', 'published_location' => 'Klaten', 'published_year' => '2009', 'book_year' => '2009','classification_code' => '920003', 'initial' => 'M','amount' => '2','category_id' => '92', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '4179','title' => 'Perjanjian-perjanjian bersejarah','author_id' => '1131', 'publisher_id' => '67', 'published_location' => 'Klaten', 'published_year' => '2009', 'book_year' => '2009','classification_code' => '920004', 'initial' => 'P','amount' => '2','category_id' => '92', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '4181','title' => 'sekitar proklamasi 17 agustus 11945','author_id' => '986', 'publisher_id' => '340', 'published_location' => 'Jakarta', 'published_year' => '2000', 'book_year' => '2000','classification_code' => '920005', 'initial' => 'S','amount' => '3','category_id' => '92', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '4184','title' => 'Ilmu pengetahuan sosial untuk SMK dan MAK kelas XI','author_id' => '65', 'publisher_id' => '122', 'published_location' => 'Jakarta', 'published_year' => '2008', 'book_year' => '2008','classification_code' => '930001', 'initial' => 'I','amount' => '1','category_id' => '91', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '4185','title' => 'Buku panduan pendidik Ilmu pengetahuan Sosial jelas X','author_id' => '1008', 'publisher_id' => '308', 'published_location' => '', 'published_year' => '2004', 'book_year' => '2004','classification_code' => '930002', 'initial' => 'B','amount' => '1','category_id' => '91', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '4186','title' => 'Buku panduan pendidik Ilmu pengetahuan Sosial jelas XI','author_id' => '1008', 'publisher_id' => '308', 'published_location' => '', 'published_year' => '2004', 'book_year' => '2004','classification_code' => '930003', 'initial' => 'B','amount' => '1','category_id' => '91', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '4187','title' => 'Ilmu Pengetahuan sosial jilid 1','author_id' => '809', 'publisher_id' => '102', 'published_location' => 'Jakarta', 'published_year' => '2009', 'book_year' => '2009','classification_code' => '930004', 'initial' => 'I','amount' => '12','category_id' => '91', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '4199','title' => 'Ilmu Pengetahuan sosial jilid 2','author_id' => '809', 'publisher_id' => '102', 'published_location' => 'Jakarta', 'published_year' => '2009', 'book_year' => '2009','classification_code' => '930005', 'initial' => 'I','amount' => '13','category_id' => '91', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '4212','title' => 'Ilmu pengetahuan sosial untuk sekolah menengah kejuruan jilid 1','author_id' => '413', 'publisher_id' => '143', 'published_location' => 'Bandung', 'published_year' => '2008', 'book_year' => '2008','classification_code' => '930006', 'initial' => 'I','amount' => '1','category_id' => '91', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '4213','title' => 'Ilmu pengetahuan sosial untuk sekolah menengah kejuruan jilid 2','author_id' => '413', 'publisher_id' => '143', 'published_location' => 'Bandung', 'published_year' => '2008', 'book_year' => '2008','classification_code' => '930007', 'initial' => 'I','amount' => '1','category_id' => '91', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '4214','title' => 'memahami IPS ilmu pengetahuan sisial 1','author_id' => '133', 'publisher_id' => '32', 'published_location' => 'Bandung', 'published_year' => '2007', 'book_year' => '2007','classification_code' => '930008', 'initial' => 'M','amount' => '1','category_id' => '91', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '4215','title' => 'memahami IPS ilmu pengetahuan sosial 2','author_id' => '388', 'publisher_id' => '32', 'published_location' => 'Bandung', 'published_year' => '2007', 'book_year' => '2007','classification_code' => '930009', 'initial' => 'M','amount' => '8','category_id' => '91', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '4223','title' => 'Indonesiaku','author_id' => '494', 'publisher_id' => '65', 'published_location' => 'Jakarta', 'published_year' => '2005', 'book_year' => '2005','classification_code' => '940001', 'initial' => 'I','amount' => '8','category_id' => '90', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '4231','title' => 'kejayaan bangsa dizaman kejayaan','author_id' => '416', 'publisher_id' => '67', 'published_location' => 'Klaten', 'published_year' => '2007', 'book_year' => '2007','classification_code' => '940002', 'initial' => 'K','amount' => '2','category_id' => '90', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '4233','title' => 'Kerajaan Majapahit','author_id' => '105', 'publisher_id' => '296', 'published_location' => '', 'published_year' => '2008', 'book_year' => '2008','classification_code' => '940003', 'initial' => 'K','amount' => '2','category_id' => '90', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '4235','title' => 'Kerajaan sriwijaya','author_id' => '105', 'publisher_id' => '296', 'published_location' => '', 'published_year' => '2008', 'book_year' => '2008','classification_code' => '940004', 'initial' => 'K','amount' => '2','category_id' => '90', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '4237','title' => 'Mengenal situs sangiran (kehidupan purba di indonesia)','author_id' => '1131', 'publisher_id' => '67', 'published_location' => 'Klaten', 'published_year' => '2008', 'book_year' => '2008','classification_code' => '940005', 'initial' => 'M','amount' => '2','category_id' => '90', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '4239','title' => 'Profil negara-negara asia tenggara','author_id' => '1149', 'publisher_id' => '67', 'published_location' => 'Klaten', 'published_year' => '2008', 'book_year' => '2008','classification_code' => '940006', 'initial' => 'P','amount' => '2','category_id' => '90', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '4241','title' => 'Riwayat samarinda dan cerita legenda kaltim','author_id' => '603', 'publisher_id' => '52', 'published_location' => 'Samarinda', 'published_year' => '2009', 'book_year' => '2009','classification_code' => '940007', 'initial' => 'R','amount' => '4','category_id' => '90', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '4245','title' => 'Masa Kecil Putra Sang Fajar','author_id' => '971', 'publisher_id' => '360', 'published_location' => 'Bandung', 'published_year' => '2006', 'book_year' => '2006','classification_code' => '950001', 'initial' => 'M','amount' => '4','category_id' => '89', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '4249','title' => 'Masa Remaja Putra Sang Fajar','author_id' => '971', 'publisher_id' => '360', 'published_location' => 'Bandung', 'published_year' => '2006', 'book_year' => '2006','classification_code' => '950002', 'initial' => 'M','amount' => '4','category_id' => '89', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '4253','title' => 'Masa Pemuda Putra Sang Fajar','author_id' => '971', 'publisher_id' => '360', 'published_location' => 'Bandung', 'published_year' => '2006', 'book_year' => '2006','classification_code' => '950003', 'initial' => 'M','amount' => '4','category_id' => '89', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '4257','title' => 'Masa Dewasa Putra Sang Fajar','author_id' => '971', 'publisher_id' => '360', 'published_location' => 'Bandung', 'published_year' => '2006', 'book_year' => '2006','classification_code' => '950004', 'initial' => 'M','amount' => '4','category_id' => '89', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '4261','title' => 'Masa Prakemerdekaan Putra Sang Fajar I','author_id' => '971', 'publisher_id' => '360', 'published_location' => 'Bandung', 'published_year' => '2006', 'book_year' => '2006','classification_code' => '950005', 'initial' => 'M','amount' => '4','category_id' => '89', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '4265','title' => 'Masa Prakemerdekaan Putra Sang Fajar II','author_id' => '971', 'publisher_id' => '360', 'published_location' => 'Bandung', 'published_year' => '2006', 'book_year' => '2006','classification_code' => '950006', 'initial' => 'M','amount' => '5','category_id' => '89', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '4270','title' => 'Masa Kemerdekaan Putra Sang Fajar','author_id' => '971', 'publisher_id' => '360', 'published_location' => 'Bandung', 'published_year' => '2006', 'book_year' => '2006','classification_code' => '950007', 'initial' => 'M','amount' => '5','category_id' => '89', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '4275','title' => 'Masa Pemerintahan Putra Sang Fajar','author_id' => '971', 'publisher_id' => '360', 'published_location' => 'Bandung', 'published_year' => '2006', 'book_year' => '2006','classification_code' => '950008', 'initial' => 'M','amount' => '4','category_id' => '89', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '4279','title' => 'Masa Senja Putra Sang Fajar','author_id' => '971', 'publisher_id' => '360', 'published_location' => 'Bandung', 'published_year' => '2006', 'book_year' => '2006','classification_code' => '950009', 'initial' => 'M','amount' => '5','category_id' => '89', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '4284','title' => 'Bung Hatta Masa Kecil','author_id' => '149', 'publisher_id' => '360', 'published_location' => 'Bandung', 'published_year' => '2009', 'book_year' => '2009','classification_code' => '950010', 'initial' => 'B','amount' => '5','category_id' => '89', 'cover' => 'f1f426bcebbc90cc85071e360afb968d.jpg', 'source' => '']);
Book::create(['no_induk' => '4289','title' => 'Bung Hatta Masa Remaja','author_id' => '149', 'publisher_id' => '360', 'published_location' => 'Bandung', 'published_year' => '2009', 'book_year' => '2009','classification_code' => '950011', 'initial' => 'B','amount' => '5','category_id' => '89', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '4294','title' => 'Bung Hatta Masa Pemuda','author_id' => '149', 'publisher_id' => '360', 'published_location' => 'Bandung', 'published_year' => '2009', 'book_year' => '2009','classification_code' => '950012', 'initial' => 'B','amount' => '5','category_id' => '89', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '4299','title' => 'Bung Hatta Masa Prakemerdekaan','author_id' => '149', 'publisher_id' => '360', 'published_location' => 'Bandung', 'published_year' => '2009', 'book_year' => '2009','classification_code' => '950013', 'initial' => 'B','amount' => '5','category_id' => '89', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '4304','title' => 'Bung Hatta Masa Kemerdekaan','author_id' => '149', 'publisher_id' => '360', 'published_location' => 'Bandung', 'published_year' => '2009', 'book_year' => '2009','classification_code' => '950014', 'initial' => 'B','amount' => '5','category_id' => '89', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '4309','title' => 'Bung Hatta Masa Pemerintahan I','author_id' => '149', 'publisher_id' => '360', 'published_location' => 'Bandung', 'published_year' => '2006', 'book_year' => '2006','classification_code' => '950015', 'initial' => 'B','amount' => '5','category_id' => '89', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '4314','title' => 'Bung Hatta Masa Pemerintahan II','author_id' => '149', 'publisher_id' => '360', 'published_location' => 'Bandung', 'published_year' => '2009', 'book_year' => '2009','classification_code' => '950016', 'initial' => 'B','amount' => '4','category_id' => '89', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '4318','title' => 'Bung Hatta Masa Pemerintahan III','author_id' => '149', 'publisher_id' => '360', 'published_location' => 'Bandung', 'published_year' => '2009', 'book_year' => '2009','classification_code' => '950017', 'initial' => 'B','amount' => '5','category_id' => '89', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '4323','title' => 'Bung Hatta Masa-Masa Terakhir','author_id' => '149', 'publisher_id' => '360', 'published_location' => 'Bandung', 'published_year' => '2008', 'book_year' => '2008','classification_code' => '950018', 'initial' => 'B','amount' => '5','category_id' => '89', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '15511','title' => 'Ratusan Jiwa Untuk Sanga-sanga','author_id' => '911', 'publisher_id' => '211', 'published_location' => 'Samarinda', 'published_year' => '2015', 'book_year' => '2015','classification_code' => '950.001.001', 'initial' => 'R','amount' => '8','category_id' => '89', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '17577','title' => 'Raih 20 Gelar dalam 13 tahun','author_id' => '1199', 'publisher_id' => '69', 'published_location' => 'Jakarta', 'published_year' => '2013', 'book_year' => '2013','classification_code' => '950.019.001', 'initial' => 'R','amount' => '1','category_id' => '89', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '4328','title' => 'Dari Pedalaman Mahakam Membangun Samarinda','author_id' => '481', 'publisher_id' => '240', 'published_location' => 'Samarinda', 'published_year' => '2010', 'book_year' => '2010','classification_code' => '951001', 'initial' => 'D','amount' => '2','category_id' => '88', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '4330','title' => 'Pengumulan H.Achmad Amins dari Awak Kapal Hingga Kursi Walikota','author_id' => '484', 'publisher_id' => '240', 'published_location' => 'Jakarta', 'published_year' => '2003', 'book_year' => '2003','classification_code' => '951002', 'initial' => 'P','amount' => '3','category_id' => '88', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '4333','title' => 'Profil anggota DPRD Kalimantan Timur','author_id' => '149', 'publisher_id' => '240', 'published_location' => 'Samarinda', 'published_year' => '2005', 'book_year' => '2005','classification_code' => '951003', 'initial' => 'P','amount' => '1','category_id' => '88', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '4334','title' => 'Politik dan Olah Raga Puncak Prestasi Emas Koni Kota Samarinda','author_id' => '347', 'publisher_id' => '240', 'published_location' => 'Samarinda', 'published_year' => '2009', 'book_year' => '2009','classification_code' => '951004', 'initial' => 'P','amount' => '2','category_id' => '88', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '17615','title' => 'Ajaran-ajaran spektakuler Bung karno & Pak Harto','author_id' => '1053', 'publisher_id' => '240', 'published_location' => 'Ircisod', 'published_year' => '2013', 'book_year' => '2013','classification_code' => '951.006.001', 'initial' => 'A','amount' => '1','category_id' => '88', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '17616','title' => 'Emong-emong Visi Pendidikan Ki Hadjar Dewantara Tantangan Dan Relevansi','author_id' => '162', 'publisher_id' => '240', 'published_location' => 'Kanisius', 'published_year' => '2013', 'book_year' => '2013','classification_code' => '951.005.001', 'initial' => 'E','amount' => '1','category_id' => '88', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '18219','title' => 'Letjen Oerip Soemohardjo','author_id' => '338', 'publisher_id' => '240', 'published_location' => 'Mutiara sumber widya', 'published_year' => '2001', 'book_year' => '2001','classification_code' => '951.007.001', 'initial' => 'L','amount' => '1','category_id' => '88', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '4336','title' => 'Einstein & Relatifitas','author_id' => '833', 'publisher_id' => '122', 'published_location' => 'Jakarta', 'published_year' => '2003', 'book_year' => '2003','classification_code' => '952001', 'initial' => 'E','amount' => '4','category_id' => '87', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '4340','title' => 'Ilmuan Besar Arestoteles','author_id' => '1018', 'publisher_id' => '271', 'published_location' => 'Bandung', 'published_year' => '2007', 'book_year' => '2007','classification_code' => '952002', 'initial' => 'I','amount' => '4','category_id' => '87', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '4344','title' => 'Ilmuan besar louis posteur','author_id' => '1018', 'publisher_id' => '271', 'published_location' => 'Bandung', 'published_year' => '2007', 'book_year' => '2007','classification_code' => '952003', 'initial' => 'I','amount' => '5','category_id' => '87', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '4349','title' => 'Ilmuan besar Tomas Edison','author_id' => '1018', 'publisher_id' => '271', 'published_location' => 'Bandung', 'published_year' => '2007', 'book_year' => '2007','classification_code' => '952004', 'initial' => 'I','amount' => '5','category_id' => '87', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '4354','title' => 'Nama-nama besar senyuman abadi leonardo da vinri','author_id' => '1158', 'publisher_id' => '271', 'published_location' => 'Bandung', 'published_year' => '2007', 'book_year' => '2007','classification_code' => '952005', 'initial' => 'N','amount' => '5','category_id' => '87', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '4359','title' => 'Nama-nama besarseleksi alam charlos darwin','author_id' => '1171', 'publisher_id' => '271', 'published_location' => 'Bandung', 'published_year' => '2007', 'book_year' => '2007','classification_code' => '952006', 'initial' => 'N','amount' => '5','category_id' => '87', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '4364','title' => 'Para penemu yang mengubah dunia','author_id' => '918', 'publisher_id' => '263', 'published_location' => 'Jakarta', 'published_year' => '2004', 'book_year' => '2004','classification_code' => '952007', 'initial' => 'P','amount' => '1','category_id' => '87', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '4365','title' => 'Penemu yang mengubah kebudayaan dunia','author_id' => '1051', 'publisher_id' => '114', 'published_location' => 'Yogyakarta', 'published_year' => '2010', 'book_year' => '2010','classification_code' => '952008', 'initial' => 'P','amount' => '4','category_id' => '87', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '4369','title' => 'Geografi aktivitas untuk menjelajahi,memetakan dan menikmati duniamu','author_id' => '197', 'publisher_id' => '271', 'published_location' => 'Bandung', 'published_year' => '2003', 'book_year' => '2003','classification_code' => '960001', 'initial' => 'G','amount' => '2','category_id' => '86', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '4371','title' => 'Gunung api aktif di indonesia','author_id' => '970', 'publisher_id' => '71', 'published_location' => 'Yogyakarta', 'published_year' => '2009', 'book_year' => '2009','classification_code' => '960002', 'initial' => 'G','amount' => '2','category_id' => '86', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '4373','title' => 'Kurs Gua batugamping, sungai bawah tanah dan mata air','author_id' => '970', 'publisher_id' => '71', 'published_location' => 'Yogyakarta', 'published_year' => '2009', 'book_year' => '2009','classification_code' => '960003', 'initial' => 'K','amount' => '2','category_id' => '86', 'cover' => '', 'source' => '']);
// Book::create(['no_induk' => '4375','title' => 'Manfaat sumberdaya ekonomi','author_id' => '624', 'publisher_id' => '', 'published_location' => '', 'published_year' => '', 'book_year' => '','classification_code' => '960004', 'initial' => 'M','amount' => '2','category_id' => '86', 'cover' => '', 'source' => '']);
// Book::create(['no_induk' => '4377','title' => 'mengenal kegiatan distribusi','author_id' => '1142', 'publisher_id' => '', 'published_location' => '', 'published_year' => '', 'book_year' => '','classification_code' => '960005', 'initial' => 'M','amount' => '2','category_id' => '86', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '4379','title' => 'Minyak bumi','author_id' => '698', 'publisher_id' => '71', 'published_location' => 'Yogyakarta', 'published_year' => '2008', 'book_year' => '2008','classification_code' => '960006', 'initial' => 'M','amount' => '2','category_id' => '86', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '18115','title' => 'Geografi untuk SMA/MA Kelas X ( K-13 )','author_id' => '620', 'publisher_id' => '284', 'published_location' => 'Jakarta', 'published_year' => '2013', 'book_year' => '2013','classification_code' => '960.007.001', 'initial' => 'G','amount' => '1','category_id' => '86', 'cover' => '', 'source' => '']);
Book::create(['no_induk' => '18220','title' => 'Atlas Indonesia dan Dunia Edisi 33 Provinsi di indonesia','author_id' => '179', 'publisher_id' => '47', 'published_location' => 'Jakarta', 'published_year' => '2013', 'book_year' => '2013','classification_code' => '960.007.001', 'initial' => 'A','amount' => '1','category_id' => '86', 'cover' => 'fa28720b6c19f75b070085bc3fec6fab.jpg', 'source' => '']);

$books =  Book::all();
foreach ($books as $key => $book) {
    $random = Carbon::today()->subDays(rand(0, 90));
    $book->created_at = $random;
    $book->updated_at = $random;
    $book->save();
}
}
}
